<?php
//require_once ('makeover_salesforce.php');
module_load_include('inc', 'print', 'print.pages');
function makeover_menu() {
	$items['send-mail'] = array(
		'title'=>'Welcome mail',
		'page callback'=>'stu_user_send_mail',
		'access arguments' => array('access profile page'),
		'type'=>MENU_CALLBACK,
		'file' => 'makeover.pages.inc'
	);
	$items['surgeons/plastic-surgeons'] = array(
		'title' => 'plastic-surgeons',
		'page callback' => 'stu_doctor_plastic_surgeons',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'makeover.pages.inc'
	);
	$items['surgeons/dental-surgeons'] = array(
		'title' => 'dental-surgeons',
		'page callback' => 'stu_doctor_dental_surgeons',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'makeover.pages.inc'
	);
	$items['admin/makeover'] = array(
		'title' => 'Stunning Makeover',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('makeover_settings'),
		'access arguments' => array('makeover admin access'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'makeover.admin.inc'
	);
	$items['admin/makeover/settings'] = array(
		'title' => 'Settings',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('makeover_settings'),
		'access arguments' => array('makeover admin access'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'makeover.admin.inc'
	);
	$items['admin/makeover/documentation'] = array(
		'title' => 'Documentation',
		'page callback' => 'makeover_docs',
		'access arguments' => array('makeover admin access'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'makeover.admin.inc'
	);
	$items['makeover/pdf'] = array(
		'page callback' => 'makeover_pdf_controller',
	  'access arguments' => array('access content'), 
		'type' => MENU_CALLBACK,
		'file' => 'makeover.pages.inc'
    );
	$items['professional-pdf-content/%'] = array(
		'page callback' => 'tlg_professional_pdf_content',
		'access arguments' => array('access content'), 
		'type' => MENU_CALLBACK,
		'file' => 'makeover.pages.inc'
    );

	$items['practice-pdf-create/%'] = array(
		//'file' => 'pdf_create/practice_pdf_template.php',
		'page callback' => 'tlg_create_practice_pdf',
		'access arguments' => array('access content'),
		'file' => 'makeover.pages.inc'
    );
	$items['professional-pdf-create/%'] = array(
		//'file' => 'pdf_create/professional_pdf_template.php',
		'page callback' => 'tlg_create_professional_pdf',
		'access arguments' => array('access content'),
		'file' => 'makeover.pages.inc'
    );
  return $items;
}

/**
 * Implementing hook_menu_alter()
 */
function makeover_menu_alter(&$items){
	$items['user/login']['type'] = MENU_CALLBACK;
	$items['user/register']['type'] = MENU_CALLBACK;
	$items['user/password']['type'] = MENU_CALLBACK;
	$items['user/login']['title'] = t('Log in');
	$items['user']['title'] = t('Log in');
}

/**
 * Implementing hook_node_load()
 */
function makeover_node_load($nodes, $types) {
  foreach ($nodes as $nid => $node) {
		if (count(array_intersect(array('procedure','packages'), $types))) {
      $node->procedure_costs = makeover_get_destination_costs($node->nid);
    }
	}
}

/**
 *  Implementing hook_node_view()
 */
function makeover_node_view($node, $view_mode, $langcode) {
  //$node->content['body']['#value'] = "<div class=\"node-body\">" . $node->content['body']['#value'] . "</div>";
}

/**
 *  Implementing hook_form_alter()
 */
function makeover_form_alter(&$form, &$form_state, $form_id) {
  
	if($form_id == 'user_login') {   //Login page
		 $form['name'] = array(
			'#type' => 'textfield', 
			'#title' => t('Email'),
			'#description' => t(''), 			
			'#size' => 30, 
			'#maxlength' => USERNAME_MAX_LENGTH, 
			'#required' => TRUE,
		 );
		 
		 $form['name']['#description'] = '';
		 $form['pass'] = array(
			'#type' => 'password', 
			'#title' => t('Password'),
			'#size' => 30, 			
			'#description' => t(''), 
			'#required' => TRUE,
		  );
		$form['#action'] = $form['#action'].'?destination=home'; 
	}

	if($form_id == 'user_pass') { //Fotgot password page
		$form['name'] = array(
			'#type' => 'textfield', 
			'#title' => t('Email'),
			'#description' => t(''), 			
			'#size' => 30, 
			'#maxlength' => USERNAME_MAX_LENGTH, 
			'#required' => TRUE,
		 );
	}
	/*if ($form_id == 'surgeon_node_form') {
	  drupal_add_css(drupal_get_path('theme', 'smo').'/css/surgeon-form.css');
	  // $form['#submit'][] = 'makeover_surgeon_form_submit';
	 // if (isset($form['nid']['#value'])) $form['#redirect'] = 'makeover/pdf/'. $form['nid']['#value'];
	  
	  /*foreach ($form as $key => $field) {
      
      if (substr($key, 0, 6) == 'field_' && is_array($field)) {
				if ($key == 'field_sg_images') continue;
				if ($field['#theme'] == 'content_multiple_values') {
					$value = 'lorem ipsum';
					switch ($field[0]['#type']) {
					case 'number':
						$form[$key][0]['#default_value']['value'] = 20;
						break;
					case 'date_combo':
						$form[$key][0]['#default_value']['value'] = '2013-05-15 00:00:00';
						break;
					default:
						$form[$key][0]['#default_value']['value'] = 'filler';
					}
				}
				else {
					if ($key == 'field_sg_gender') $form[$key]['#default_value'][0]['value'] = 'Male';
					else $form[$key]['#default_value'][0]['value'] = 'No';
				}
		}
		
		// Removed required from all fields
		if (strpos($key, 'field_') !== FALSE) {
			$form[$key][LANGUAGE_NONE][0]['#required'] = FALSE;
			$form[$key][LANGUAGE_NONE]['#required'] = FALSE;
		}
	}
 }*/
	
	if ($form_id == 'procedure_node_form' || $form_id == 'packages_node_form') {
	  // Enable costs per destination to be stored
	  /*$destinations = makeover_destinations_select('nid');
	  $costs = makeover_get_destination_costs($form['nid']['#value']);
	  $c = 0;
	  foreach ($destinations as $nid => $destination) {
	    $form['procedure_costs_'. $nid] = array(
		  '#title' => 'Cost: '. $destination,
		  '#type' => 'textfield',
		  '#size' => 12,
		  '#weight' => 8,
		  '#default_value' => $costs[$nid],
		  '#attributes' => array('class' => 'text')
		);
		if ($form_id == 'packages_node_form') {
		   $form['procedure_costs_'. $nid]['#weight'] = 0;
		}
	  }
	  $form['#submit'][] = 'makeover_procedure_submit';*/
	}
	 if($form_id == 'webform_client_form_107') //Quotation Webform
	{   	
	    
		//db_query("UPDATE {system} SET weight=10 WHERE name='makeover'");
		if($form_state['webform']['page_num'] == 1) { //page1
	        $form['submitted']['first_name']['#default_value'] = 'Joe';
	        $form['submitted']['last_name']['#default_value'] = 'Sample';
	        $form['submitted']['gender']['#default_value'] = 'male';
	        $form['submitted']['country_of_residence']['#default_value'] = 'NZ';
	        $form['submitted']['city']['#default_value'] = 'Hastings';
	        $form['submitted']['phone_number']['#default_value'] = '12345678';
	        $form['submitted']['email_address']['#default_value'] = 'kent@passingphase.co.nz';
			$user_pass = makeover_generate_password(10);     //makeover_generate_password
			$form['submitted']['user_pass']['#default_value'] = $user_pass;    //set password to user_pass [37] field
			$form['#validate'][] = 'makeover_webform_client_form_107_validate_p1';
			// unset($form['actions']['captcha']);
			//watchdog('stunning', 'form <pre>'. print_r($form,1) .'</pre>');
			unset($form['mollom']);
			foreach ($form['#after_build'] as $key => $function) {
			  if ($function == 'mollom_form_buttons_after_build') unset ($form['#after_build'][$key]);
			}
		}
		if($form_state['webform']['page_num'] == 2) {  //page2 
		    // Replace destination options with full options
			
			$form['submitted']['preferred_destination']['#options'] = makeover_destinations_select('name');
			list($ex_y,$ex_m,$ex_d) = explode('-',date('Y-n-j',mktime(0,0,0,date('m'),date('d'),date('Y'))));
			$form['submitted']['departing']['#default_value'] = array('year' => $ex_y, 'month' => $ex_m, 'day' => $ex_d);
			$form['submitted']['returning']['#default_value'] = array('year' => $ex_y, 'month' => $ex_m, 'day' => $ex_d);
		
			$form['#submit'][] = 'makeover_webform_client_form_107_submit';  // when click submit go to function makeover_webform_client_form_107_submit
			$form['#validate'][] = 'makeover_webform_client_form_107_validate_p2'; //call function makeover_webform_client_form_107_validate
			unset($form['submitted']['fromcity_or_airport']['#options'][1]); //remove option value for "From(city or airport)"
			unset($form['submitted']['tocity_or_airport']['#options'][1]); //remove option value for "To(city or airport)"
			
			$results = views_get_view_result('all_city', 'defaults');
			foreach($results as $result){
				$city_name =  $result->node_title;
				$form['submitted']['fromcity_or_airport']['#options'][$city_name] =  $city_name; //Set option value for "From(city or airport)"
				$form['submitted']['tocity_or_airport']['#options'][$city_name] =  $city_name; //Set option value for "To(city or airport): "
			}
		}
	}
}
/*
 *  Helper function to supply list of destinations 
 *  @type is nid, to use nid as key, or name, to use name as key
 */
function makeover_destinations_select($type = 'nid') {
  static $options;
  if (!$options[$type]) {
    $destinations = views_get_view_result('Destination',null);	
    	
    $options[$type] = array();
    foreach ($destinations as $destination) {
	  if ($type == 'nid') $options[$type][$destination->nid] = $destination->node_title;
      else $options[$type][$destination->node_title] = $destination->node_title;
    } 
	if ($type == 'name') $options[$type]['No Preference'] = 'No Preference';
  }
  return $options[$type];
}

/**
 * 
 */
function makeover_get_destination_costs($nid) {
	$query = db_select('makeover_procedure_costs', 'n');
	$query->fields('n');
	$query->condition('n.procedure_nid', $nid, '=');
  $result = $query->execute();
  $records = $result->fetchAll();
  foreach($records AS $record) {
		$values[$record->destination_nid] = $record->cost;
  }
  return $values;
}

/**
 * 
 */
function makeover_procedure_validate($form, &$form_state) {
  $values = $form_state['values'];
  foreach ($values as $key => $value) {
    if (substr($key, 0, 15) == 'procedure_costs') {
	    if (!is_numeric($value)) form_set_error($key, 'The cost value should be numeric only');
	  }
  }
}

/**
 * Submit Callback
 */
function makeover_procedure_submit($form, &$form_state) {
  $values = $form_state['values'];
  db_delete('makeover_procedure_costs')
    ->condition('procedure_nid', $values['nid'])
    ->execute();
  
  foreach ($values as $key => $value) {
    if (substr($key, 0, 15) == 'procedure_costs') {
	    $parts = explode('_', $key);
	    // Insert query here
	    $nid = db_insert('makeover_procedure_costs')
				->fields(array(
					'destination_nid' => $parts[2],
					'procedure_nid' => $values['nid'],
					'cost' => $value,
				))
				->execute();
	  }
  }
}


/**
 * Webform submit handler
 */ 
function makeover_webform_client_form_107_submit($form, &$form_state) {
	
	if ($form_state['values']['op'] == '< Previous Page') return;
	$uid = db_select('users','u')
	       -> fields('u',array('uid'))
	       -> conditions('name', $form_state['values']['submitted'][8], '=')
	       -> execute()->fetchField();
	       
	if($uid == '' || $uid == null){
		//create user
		$account = user_save(null, array(
				'name' => $form_state['values']['submitted'][8], //user name
				'mail' => $form_state['values']['submitted'][8], 
				'status' => 1 , 
				'pass' => $form_state['values']['submitted'][37] , 
				'roles' => 3 
			)
		);
																
		makeover_set_roles($account->uid, 'other_user'); //set role for user
		$user_id = $account->uid;
	}
	else {
		$user_id = $results[uid];
		//$form['submitted']['user_pass']['#default_value'] = '';
	}
	
	//Save to makeover_salesforce
	$data = array();
	
	$data['name'] = $form_state['values']['submitted'][1]." ".$form_state['values']['submitted'][2];
	$data['firstname'] = $form_state['values']['submitted'][1];
	$data['lastname'] = $form_state['values']['submitted'][2];
	$data['gender'] = $form_state['values']['submitted'][3];
	list($ex_y,$ex_m,$ex_d) = explode('-',$form_state['values']['submitted'][4]);
	$data['date_of_birth'] = mktime(0, 0, 0, $ex_m, $ex_d, $ex_y);
	//$data['date_of_birth'] = $form_state['values']['submitted'][4];
	
	$data['country'] = $form_state['values']['submitted'][5];
	$data['city'] = $form_state['values']['submitted'][6];
	$data['email'] = $form_state['values']['submitted'][8];
	
	$data['preferred_destination'] = $form_state['values']['submitted'][10];
	list($ex_y,$ex_m,$ex_d) = explode('-',$form_state['values']['submitted'][11]);
	$data['have_surgery'] = mktime(0, 0, 0, $ex_m, $ex_d, $ex_y);
	//$data['have_surgery'] = $form_state['values']['submitted'][11];
	$data['travelling_with_others'] = $form_state['values']['submitted'][12];
	$data['how_many'] = $form_state['values']['submitted'][13];
	$data['accommodation'] = $form_state['values']['submitted'][14];
	$data['airfares'] = $form_state['values']['submitted'][15];
	$data['from'] = $form_state['values']['submitted'][16];
	$data['to'] = $form_state['values']['submitted'][18];
	if($data['airfares'] == 'yes'){
		list($ex_y,$ex_m,$ex_d) = explode('-',$form_state['values']['submitted'][17]);
		$data['departing'] = mktime(0, 0, 0, $ex_m, $ex_d, $ex_y);
		//$data['departing'] = $form_state['values']['submitted'][17];
		list($ex_y,$ex_m,$ex_d) = explode('-',$form_state['values']['submitted'][19]);
		$data['returning'] = mktime(0, 0, 0, $ex_m, $ex_d, $ex_y);
		//$data['returning'] = $form_state['values']['submitted'][19];
	}
	else {
		$data['departing'] = 'null';
		$data['returning'] = 'null';
	}
	
	//echo makeover_diffdate(date("Y-m-d",$data['departing']),date("Y-m-d",$data['returning']));
	//exit
	
	$data['airport_tranfers'] = $form_state['values']['submitted'][20];
	$data['hospital_transfers'] = $form_state['values']['submitted'][21];
	$data['how_did_you_find'] = $form_state['values']['submitted'][22];
	$data['contact_you_by_phone'] = $form_state['values']['submitted'][23];
	$data['contact_number'] = $form_state['values']['submitted'][31];
	$data['specials_and_updates'] = $form_state['values']['submitted'][24];
	
	$results = views_get_view_result('get_flight_cost',null,$form_state['values']['submitted'][16],$form_state['values']['submitted'][18]); 
	$data['flight_nid'] = $results[0]->nid;
	
	$data['non_surgical_nid'] = $form_state['values']['submitted'][48];
	$data['plastic_surgery_nid'] = $form_state['values']['submitted'][38];
	$data['dental_procedures_nid'] = $form_state['values']['submitted'][39];
	$data['dental_procedures_nid_2'] = $form_state['values']['submitted'][40];
	$data['dental_procedures_nid_3'] = $form_state['values']['submitted'][41];
	$data['packages_nid'] = $form_state['values']['submitted'][42];
	
	$data['a_body_part'] = $form_state['values']['submitted'][47];
	$data['a_tooth'] = $form_state['values']['submitted'][30];
	$data['a_tooth_2'] = $form_state['values']['submitted'][34];
	$data['a_tooth_3'] = $form_state['values']['submitted'][36];
	
	//watchdog('makeover', 'values submitted<pre>'. print_r($form_state['values']['submitted'],1). '</pre>');
	$data['plastic_surgery'] = $form_state['values']['submitted'][26];
	$data['packages'] = $form_state['values']['submitted'][28];
	$data['dental_procedures_1'] = $form_state['values']['submitted'][27];
	$data['dental_procedures_2'] = $form_state['values']['submitted'][33];
	$data['dental_procedures_3'] = $form_state['values']['submitted'][35];
	
	//more info
	$data['terms_conditions'] = $form_state['values']['submitted'][25];
	$data['phone_number'] = $form_state['values']['submitted'][29];
	$current_time = strtotime("now");
	
	$data['currency_value'] = $form_state['values']['submitted'][43];
	$data['currency_format'] = $form_state['values']['submitted'][44];
	makeover_salesforce($data);
	
	//Save data to custom table
	$stu_uid = makeover_chk_already_stu_user($user_id);

	if($stu_uid){
		// echo 'already'.$stu_uid;
		// exit;
		//create qoutation
		makeover_insert_quotation($data,$stu_uid);

	}
	else {
		//create new user(custom table)
		db_insert('stu_user')
		-> fields(array(
		  'firstname' => $form_state['values']['submitted'][1],
		  'lastname' => $form_state['values']['submitted'][2],
		  'gender' => $data['gender'],
		  'dateofbirth' => $data['date_of_birth'],
		  'country' => $data['country'],
		  'city' => $data['city'],
		  'phone' => $data['phone_number'],
		  'email' => $data['email'],
		  'user_id' => $user_id,
		  'createddate' => $current_time
		))
		 ->execute();
		
		//get last user in stu_user
		$stu_new_id = makeover_get_stu_user();
		
    //create qoutation(custom table)
		makeover_insert_quotation($data,$stu_new_id);
	}
	
	//send email to admin(site infomation:email)
	makeover_send_email_admin($data);
}
 
function makeover_set_roles($uid, $role) {
	$roles = user_roles(TRUE);
	foreach( $roles as $key => $name ) {
		if($name == $role){
			db_insert('users_roles')
			->fields(array(
			 'rid' => $key,
			 'uid' => $uid,
			))
			->execute();
		}
	}
}

/**
 * Generate password
 */
function makeover_generate_password($length){
	$random= "";
	srand((double)microtime()*1000000);
	$data = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
	for($i = 0; $i < $length; $i++) {
		 $random .= substr($data, (rand()%(strlen($data))), 1);
	}
  return $random;
}

/**
 * Validat email
 */
function makeover_validatemail($mail) {
  if($mail !== "") {
    if(ereg("^[-A-Za-z0-9_]+[-A-Za-z0-9_.]*[@]{1}[-A-Za-z0-9_]+[-A-Za-z0-9_.]*[.]{1}[A-Za-z]{2,5}$", $mail)) {
      return true;
    } else {
      return false;
    }
  } else {
    return false;
  }
} 

/**
 * Implementation of hook_permission
 */
function makeover_permission(){
	return array(
	  'makeover admin access' => array (
      'title' => t('Access Makeover'),
      'description' => t('Display the administration menu at the top of each page.'),
    ),
		'access register page' => array (
      'title' => t('Access Register Page'),
     ),
		'access profile page' => array (
      'title' => t('Access Register Page'),
     ),
		'access register js' => array (
      'title' => t('Access Register Js'),
     ),
		'access questionare page' => array (
      'title' => t('Access Questionare Page'),
     ),
		'access questionare js' => array (
      'title' => t('Access Questionare Js'),
     ),
		'access profile js' => array (
      'title' => t('Access Profile Js'),
     ),
		'access lightbox' => array (
      'title' => t('Access Lightbox'),
     ),
		'access email test' => array (
      'title' => t('Access Email Test'),
     ),
	);
}


/**
 * Implementation of hook_user_view()
 */
function makeover_user_view($account, $view_mode, $langcode) {
  $account->content['surgeons_form'] = array(
	  '#type' => 'user_profile_category',
	  '#title' => t('Surgeon\'s form'),
	  'add_new' => array(
	    '#type' => 'user_profile_item',
        '#value' => l('Create new surgeon\'s form', 'node/add/sugeon'),
        '#weight' => 4,
	  ),
	  'edit_view' => array(
	    '#type' => 'user_profile_item',
        '#value' => views_embed_view('SurgeonsForms', 'block_1', arg(1)),
        '#weight' => 4,
	  ),
  );
}
 
/**
 * Implements hook_block_info()
 */
function makeover_block_info() {
  $blocks['pkg_left'] = array(
    'info' => t('Makeover Package Left Menu'),
    'status' => TRUE,
    'region' => -1,
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['pkg_landing'] = array(
    'info' => t('Makeover Package Landing Page'),
    'status' => TRUE,
    'region' => -1,
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['converter'] = array(
    'info' => t('Makeover Converter'),
    'status' => TRUE,
    'region' => -1,
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['pricelist_converter'] = array(
    'info' => t('Makeover Pricelist Converter'),
    'status' => TRUE,
    'region' => -1,
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['destination_left_menu'] = array(
    'info' => t('Makeover Destination Left Menu'),
    'status' => TRUE,
    'region' => -1,
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['doctor_left_menu'] = array(
    'info' => t('Makeover Doctor Left Menu'),
    'status' => TRUE,
    'region' => -1,
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['doctor_landing_page'] = array(
    'info' => t('Makeover Doctor Landing Page'),
    'status' => TRUE,
    'region' => -1,
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['makeover_footer'] = array(
    'info' => t('Makeover Footer'),
    'status' => TRUE,
    'region' => -1,
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['makeover_homepage_destination'] = array(
    'info' => t('Makeover homepage destination'),
    'status' => TRUE,
    'region' => -1,
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['makeover_homepage_packages'] = array(
    'info' => t('Makeover homepage packages'),
    'status' => TRUE,
    'region' => -1,
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['makeover_homepage_testimonials'] = array(
    'info' => t('Makeover homepage testimonials'),
    'status' => TRUE,
    'region' => -1,
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['makeover_price_list'] = array(
    'info' => t('Makeover Price List'),
    'status' => TRUE,
    'region' => -1,
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['makeover_procedure_group'] = array(
    'info' => t('Makeover Procedure Group'),
    'status' => TRUE,
    'region' => -1,
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['makeover_video'] = array(
    'info' => t('Makeover video'),
    'status' => TRUE,
    'region' => -1,
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['makeover_facebook_feed'] = array(
    'info' => t('Makeover Facebook Feed'),
    'status' => TRUE,
    'region' => -1,
    'cache' => DRUPAL_NO_CACHE
  );
  return $blocks;
}

/**
 * Implementing hook_block_view()
 */
function makeover_block_view($delta = '') {
	$block = array();
  switch ($delta) {
		
    case 'pkg_left':
      $block['subject'] = NULL;
      $block['content'] = makeover_package_menu_block();
    break;
    
    case 'pkg_landing':
      $block['subject'] = NULL;
      $block['content'] = makeover_package_landingpage_block();
    break;
    
    case 'converter':
      $block['subject'] = NULL;
      $block['content'] =  drupal_get_form('makeover_converter');
    break;
    
    case 'pricelist_converter':
      $block['subject'] = NULL;
      $block['content'] = makeover_pricelist_converter_block();
    break;
    
    case 'destination_left_menu':
      $block['subject'] = NULL;
      $block['content'] = makeover_destionationmenu_block();
    break;
    
    case 'doctor_landing_page':
      $block['subject'] = NULL;
      $block['content'] = makeover_doctor_landingpage_block();
    break;
    
    case 'doctor_left_menu':
      $block['subject'] = NULL;
      $block['content'] = makeover_doctor_block();
    break;
    
    case 'makeover_footer':
      $block['subject'] = NULL;
      $block['content'] = makeover_footer_block();
    break;
    
    case 'makeover_homepage_destination':
      $block['subject'] = l(t('Destinations'),'node/96', array('attributes' => array('class' => 'block-left'))) .' ' . l(t('View All'),'node/96', array('attributes' => array('class' => 'block-right')));
      $block['content'] =  makeover_homepage_destination();
    break;
    
    case 'makeover_homepage_packages':
      $block['subject'] = l(t('Special Packages'),'node/73', array('attributes' => array('class' => 'block-left'))) .' ' .
      l(t('View All'),'node/73', array('attributes' => array('class' => 'block-right')));
      $block['content'] = makeover_homepage_packages();
    break;
    
    case 'makeover_homepage_testimonials':
      $block['subject'] = l(t('What Clients Say'),'node/28', array('attributes' => array('class' => 'block-left'))) .' ' .
      l(t('View All'),'node/28', array('attributes' => array('class' => 'block-right')));
      $block['content'] = markup_homepage_testimonials();
    break;
    
    case 'makeover_price_list':
      $block['subject'] = NULL;
      $block['content'] = makeover_pricelist_block();
    break;
    
    case 'makeover_procedure_group':
      $block['subject'] = NULL;
      $block['content'] = makeover_procedurelist_block();
    break;
    
    case 'makeover_video':
      $block['subject'] = NULL;
      $block['content'] = makeover_video_block();
    break;
    case 'makeover_facebook_feed':
      $block['subject'] = NULL;
      $block['content'] = makeover_facebook_feed_block();
    break;
	}
	return $block;
}

/**
 * Facebook feed
 */

function makeover_facebook_feed_block() {
  $output = theme('makeover_facebook_feed');
    return   $output;	
}

/**
 * Currency Converter
 */
function makeover_converter($form, &$form_state) {
	$preferred_currency = field_info_field('field_preferred_currency');
  $options = $preferred_currency['settings']['allowed_values'];
  $form['converter_currency'] = array(
    '#title' => 'Convert Your Currency',
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => array($_SESSION['CURR']),
  );
  return $form;
}



function makeover_footer_block() {
	$output = theme('stu_footer');
	return   $output;  
}

/**
 * Implementing hook_theme()
 */
function makeover_theme($existing, $type, $theme, $path) {
  $path = drupal_get_path('module', 'makeover') .'/templates';
	return array(
		'stu_package' => array(
		  'variables' => array(),
		  'template' => 'stu_package',
		  'path' => $path
		),		
		'stu_package_landing' => array(
		  'variables' => array(),
		  'template' => 'stu_package_landing',
		  'path' => $path
		),	
		/*'user_login' => array(
		  'render element' => 'form',
		  'template' => 'user_login',
		  'path' => $path
		),*/
		'user_pass' => array(
		  'render element' => 'form',
		  'template' => 'user_pass',
		  'path' => $path
		),
		'stu_destionationmenu' => array(
		  'variables' => array(),
		  'template' => 'stu_destionationmenu',
		  'path' => $path
		),		
		'stu_doctor' => array(
		  'arguments' => array(),
		  'template' => 'stu_doctor',
		  'path' => $path
		),		
		'stu_doctor_landing' => array(
		  'variables' => array(),
		  'template' => 'stu_doctor_landing',
		  'path' => $path
		),	
		'stu_footer' => array(
		  'variables' => array(),
		  'template' => 'stu_footer',
		  'path' => $path
		),		
		'stu_pricelist' => array(
		  'arguments' => array(),
		  'template' => 'stu_pricelist',
		  'path' => $path
		),		
		'stu_procedurelist' => array(
		  'variables' => array(),
		  'template' => 'stu_procedurelist',
		  'path' => $path
		),		
		'stu_video' => array(
		  'variables' => array(),
		  'template' => 'stu_video',
		  'path' => $path
		),		
		'surgeon_node_form' => array(
		  'render element' => 'form',
		  'template' => 'node-form-surgeon',
		  'path' => drupal_get_path('theme', 'smo').'/templates'
		),
		'makeover_facebook_feed' => array(
		  'variables' => array(),
		  'template' => 'makeover-facebook-feed',
		  'path' => $path
		),
	); 
}

/*-----------contact form--------------------*/
/**
 * Implementing Hook_mail_alter()
 */
function makeover_mail_alter(&$message) {
	switch($message['id']) {
    case 'contact_page_mail':
    
    $name = $message['params']['name'];
    $body = 'EMAIL FROM STUNNINGMAKERS.COM CONTACT FORM';
	  $body .= '<br/>';
    $body .= 'DATE SENT: '.date("d/m/Y"); 
	  $body .= '<br/>';
    $body .= 'TIME SENT: '.date("H:i:s");
    $body .= '<br/>';
	  $body .= '<br/>';
    $body .= 'NAME: '.$message['params']['name'];
	  $body .= '<br/>';
    $body .= 'EMAIL ADDRESS: '.$message['params']['mail'];
	  $body .= '<br/>';
	  $body .= '<br/>';
    $body .= 'SUBJECT: '.$message['params']['subject'];
	  $body .= '<br/>';
	  $body .= '<br/>';
    $body .= 'MESSAGE: '.$message['params']['message'];
	  
	  $message['body'] = $body; 
	  break;
	  
	  case 'makeover_quote_form':
     $message['headers']['Bcc'] = variable_get('bcc_notification_receiver', '');
     //watchdog("altermaildebug", '<pre>' . print_r( $message, true) . '</pre>'); 
    break;
	  
  }
}

/**
 * Implementing Hook_mail()
 */
function makeover_mail($key, &$message, $params) {
	$options = array(
    'langcode' => $message['language']->language,
  );
  switch ($key) {
    // Send a simple message from the contact form.
    case 'surgeon_form_attachment':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      print_r($params);
      die;
      if (sizeof($params['attachment']) > 0) {
				foreach ($params['attachment'] as $attachment) {
          $message['params']['attachments'][] = $attachment;
				}
			}
      break;
    
    case 'surgeon_form':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
      
    case 'quote_form':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      //watchdog("maildebug", '<pre>' . print_r( $message, true) . '</pre>'); 
    break;
    
    case 'quote_form_staff':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
    break;
  }
}

/**
 * 
 */
function makeover_insert_quotation($data,$stu_id) {
	$current_time = strtotime("now");
    if (isset($data['a_body_part']) && $data['a_body_part'] != '') {
	  $surgical_procedure = $data['plastic_surgery_nid'] . ' liposuction: '. $data['a_body_part'];
	  if ($data['non_surgical_nid']) $surgical_procedure = $surgical_procedure .','. $data['non_surgical_nid'];
	}
	else {
	  $surgical_procedure = $data['plastic_surgery_nid'];
	  if ($surgical_procedure != '') {
	    if ($data['non_surgical_nid']) $surgical_procedure = $surgical_procedure .','. $data['non_surgical_nid'];
	  }
	  else $surgical_procedure = $data['non_surgical_nid'];
	}
	// Insert Query
	db_insert('stu_quotation')
	->fields(array(
	    'procedure_surgical' => $surgical_procedure,
	    'procedure_dental_1' => $data['dental_procedures_nid'],
	    'procedure_dental_2' => $data['dental_procedures_nid_2'],
	    'procedure_dental_3' => $data['dental_procedures_nid_3'],
	    'procedure_dental_tooth_1' => $data['a_tooth'],
	    'procedure_dental_tooth_2' => $data['a_tooth_2'],
	    'procedure_dental_tooth_3' => $data['a_tooth_3'],
	    'procedure_packages' => $data['packages_nid'],
	    'trip_destination' => $data['preferred_destination'],
	    'trip_plan' => $data['have_surgery'],
	    'trip_travelling' => $data['travelling_with_others'],
	    'trip_person' => $data['how_many'],
	    'accommodation' => $data['accommodation'],
	    'airfares' => $data['airfares'],
	    'airfares_from' => $data['from'],
	    'airfares_to' => $data['to'],
	    'airfares_departing' => $data['departing'],
	    'airfares_returning' => $data['returning'],
	    'airport_transfers' => $data['airport_tranfers'],
	    'hospital_transfers' => $data['hospital_transfers'],
	    'how_to_findout' => $data['how_did_you_find'],
	    'contact' => $data['contact_you_by_phone'],
	    'contact_number' => $data['contact_number'],
	    'informed_update' => $data['specials_and_updates'],
	    'terms' => $data['terms_conditions'],
	    'uid' => $stu_id,
	    'createddate' => $current_time,
	  )
	)
	->execute();
}

function makeover_chk_already_stu_user($user_id) {
	$uid = db_select('stu_user','u')
		 -> fields('u',array('uid'))
		 -> conditions('u.stu_user', $user_id, '=')
		 -> execute()->fetchField();
  return $uid;
}

function makeover_get_stu_user() {
	$uid = db_select('stu_user','u')
		 -> fields('u',array('uid'))
		 -> orderBy('u.uid', 'ASC')
		 -> execute()->fetchField();
  return $uid;
}

function makeover_send_email_admin($data){
	//--send email admin
	$subject = 'STUNNINGMAKERS.COM ENQUIRY FORM';		
	// $params = array(
		// 'subject' => $subject,
		// 'vendor_name'=> $info['firstname'].' '.$info['lastname']
	// );
	
	//--send email notification to admin
	$body = 'EMAIL FROM STUNNINGMAKERS.COM ENQUIRY FORM';
	$body .= '<br/>';
	$body .= 'DATE SENT: '.date("d/m/Y"); 
	$body .= '<br/>';
	$body .= 'TIME SENT: '.date("H:i:s");
	$body .= '<br/>';
	$body .= '<br/>';
	
	$body .= 'FIRST NAME: '.$data['firstname'];
	$body .= '<br/>';
	$body .= 'LAST NAME: '.$data['lastname'];
	$body .= '<br/>';
	$body .= '<br/>';
	
	$body .= 'GENDER: '.$data['gender'];
	$body .= '<br/>';
	$body .= 'DOB: '.date("d/m/Y",$data['date_of_birth']);
	$body .= '<br/>';
	$body .= '<br/>';
	
	$body .= 'EMAIL ADDRESS: '.$data['email'];
	$body .= '<br/>';
	$body .= 'TELEPHONE NUMBER: '.$data['phone_number'];
	$body .= '<br/>';
	$body .= '<br/>';
	
	$body .= 'COUNTRY OF RESIDENCE: '.$data['country'];
	$body .= '<br/>';
	$body .= 'CITY: '.$data['city'];
	$body .= '<br/>';
	$body .= '<br/>';
	
	$body .= 'PROCEDURES OF INTEREST: <br/>'.$data['plastic_surgery'];
	$body .= '<br/>';
	$body .= '<br/>';
	
	$body .= 'DENTAL PROCEDURES: <br/>'.$data['dental_procedures_1'];
	if($data['dental_procedures_2']){
		$body .= ', '.$data['dental_procedures_2'];
	}
	if($data['dental_procedures_3']){
		$body .= ', '.$data['dental_procedures_3'];
	}
	$body .= '<br/>';
	$body .= 'TEETH SELECTED: <br/>'.$data['a_tooth'];
	if($data['a_tooth_2']){
		$body .= '; '.$data['a_tooth_2'];
	}
	if($data['a_tooth_3']){
		$body .= '; '.$data['a_tooth_3'];
	}
	$body .= '<br/>';
	$body .= '<br/>';
	
	$body .= 'PREFERRED DESTINATION: '.$data['preferred_destination'];
	$body .= '<br/>';
	$body .= 'DATE OF SURGERY: '.date("d/m/Y",$data['have_surgery']);
	$body .= '<br/>';
	$body .= '<br/>';
	
	$body .= 'TRAVELLING WITH OTHERS: '.$data['travelling_with_others'];
	$body .= '<br/>';
	$body .= 'HOW MANY PEOPLE: '.$data['how_many'];
	$body .= '<br/>';
	$body .= 'ACCOMMODATION REQUIRED: '.$data['accommodation'];
	$body .= '<br/>';
	$body .= '<br/>';
	
	$body .= 'AIRFARES REQUIRED: '.$data['airfares'];
	$body .= '<br/>';
	$body .= 'FROM CITY: '.$data['from'];
	$body .= '<br/>';
	$body .= 'TO CITY: '.$data['to'];
	$body .= '<br/>';
	if (is_numeric($data['departing'])) {
	  $body .= 'DEPART DATE: '.date("d/m/Y",$data['departing']);
	}
	$body .= '<br/>';
	if (is_numeric($data['returning'])) {
	  $body .= 'RETURN DATE: '.date("d/m/Y",$data['returning']);
	}
	$body .= '<br/>';
	$body .= 'AIRPORT TRANSFERS: '.$data['airport_tranfers'];
	$body .= '<br/>';
	$body .= 'HOSPITAL TRANSFERS: '.$data['hospital_transfers'];
	$body .= '<br/>';
	$body .= '<br/>';
	
	$body .= 'HOW DID FIND OUT ABOUT US: '.$data['how_did_you_find'];
	$body .= '<br/>';
	$body .= 'CAN CONTACT BY PHONE: '.$data['contact_you_by_phone'];
	$body .= '<br/>';
	$body .= 'CONTACT NUMBER: '.$data['contact_number'];
	$body .= '<br/>';
	$body .= '<br/>';
	
	$body .= 'INFORM ABOUT UPDATES & SPECIALS: '.$data['specials_and_updates'];
	$body .= '<br/>';
	$body .= 'AGREE TO T&Cs: '.$data['terms_conditions'];
	$body .= '<br/>';
	$body .= '<br/>';
	
	$params = array(
		'subject' => $subject,
		'body' => $body
	);
	
	$mail_to = 'wiwat@dotography.com'; //admin site
	$mail_to = 'kent@passingphase.co.nz';
	$mail_from = $data['email'];
	drupal_mail('htmlmail', 'admin', $mail_to, language_default(), $params,$mail_from);
}

//receive formmat Y-m-d
function makeover_diffdate($datefrom,$dateto) {
	$diff = abs(strtotime($dateto) - strtotime($datefrom));
  $years = floor($diff / (365*60*60*24));
	$months = floor(($diff - $years * 365*60*60*24) / (30*60*60*24));
	$days = floor(($diff - $years * 365*60*60*24 - $months*30*60*60*24)/ (60*60*24));
  return $days.$months.$years;
}

//receive formmat Y-m-d
function makeover_diffdatebyDay($strDate1,$strDate2) {
  return (strtotime($strDate2) - strtotime($strDate1))/  ( 60 * 60 * 24 );  // 1 day = 60*60*24
}
 /*
 *  Block callbacks
 */
function makeover_package_menu_block() {
	$output = theme('stu_package');
	return   $output;  
}

function makeover_package_landingpage_block() {
	$output = theme('stu_package_landing');
	return $output;  
}

function makeover_converter_block() {
	/*$html = 'Convert to <select onChange="converter_currency(this.value);" id ="currency_converter" name="currency_converter">';
  $html .= '<option value="_none">- Select a value -</option>';
	if (sizeof($options) > 0) {
		foreach ($options as $key => $value) {
		  $html .= '<option value="'.$key.'">'.$value.'</option>';	
		}
	} 
  $html .= '</select>';
  */
  /*$html =  "<!-- Dynamic Converter --> 
				<script language='JavaScript' type='text/javascript'> 
				function dc_ld() { 
				var dc_dlay = document.createElement('script'); 
				dc_dlay.setAttribute('type', 'text/javascript'); 
				dc_dlay.setAttribute('language', 'javascript'); 
				dc_dlay.setAttribute('id', 'dcdlay'); 
				dc_dlay.setAttribute('src', 'http'+(window.location.protocol.indexOf('https:')==0?'s://converter':'://converter2')+'.dynamicconverter.com/accounts/10/10452'+'.'+'js'); 
				document.getElementsByTagName('head')[0].appendChild(dc_dlay);
				 } setTimeout('dc_ld()',10); 
				 </script>
				<a href='http://dynamicconverter.com' style='display: none;'>Free currency conversion</a>
				<div class='convert-from'>
					<p>From<span id='convert' amount='".$cost."' ></span></p>
					
				</div>
				<div class='convert-to'>
					Convert to<br/>
					<span id='currency_select'>
					</span>
				</div>";
			;*/
	return $html;
}

function makeover_pricelist_converter_block() {
  $node = node_load(arg(1));
	$cost = '';
	
	if($node->type == "packages") {
		$field_package_price = field_get_items('node', $node, 'field_package_price');
		$cost =  $field_package_price['0']['value'];
	}
	if($node->type == "procedure") {
		$field_procedure_cost = field_get_items('node', $node, 'field_procedure_cost');
		$cost =  $field_procedure_cost['0']['value'];
  }
	/*$html =  "<!-- Dynamic Converter --> 
				<script language='JavaScript' type='text/javascript'> 
				function dc_ld() { 
				var dc_dlay = document.createElement('script'); 
				dc_dlay.setAttribute('type', 'text/javascript'); 
				dc_dlay.setAttribute('language', 'javascript'); 
				dc_dlay.setAttribute('id', 'dcdlay'); 
				dc_dlay.setAttribute('src', 'http'+(window.location.protocol.indexOf('https:')==0?'s://converter':'://converter2')+'.dynamicconverter.com/accounts/10/10452'+'.'+'js'); 
				document.getElementsByTagName('head')[0].appendChild(dc_dlay);
				 } setTimeout('dc_ld()',10); 
				 </script>
				<a href='http://dynamicconverter.com' style='display: none;'>Free currency conversion</a>
				<div class='convert-to'>
					Convert to<br/>
					<span id='currency_select'></span>
				</div>";
			;*/
				
	return $html;
}

function makeover_destionationmenu_block() {
	$output = theme('stu_destionationmenu');
	return   $output;  
}

function makeover_doctor_block() {
	$output = theme('stu_doctor');
	return   $output;  
}

function makeover_doctor_landingpage_block() {
	$output = theme('stu_doctor_landing');
	return $output;  
}

function makeover_homepage_destination(){
	$results = views_get_view_result('home_destinations', null);
	$count = count($results);		
	$result = $results[0];
	$title = $result->node_title;
	$node = node_load($result->nid);
	$image = $node->field_destination_image[LANGUAGE_NONE][0]["filepath"];
	$body = $result->node_revisions_body;
	
	//$destination_id = 'node/'.$result->nid;
	//$path = drupal_get_path_alias($destination_id);
	
	$content = "<div id='home-destination'>";
	$content .= "<div id='destination-content'>";
	if($count){
		$content .= "<div class='destination-content-page'>";
		 if($count==1){
				$content .= "<span class='page-number-dummy' style='height:18px; display:block;'></span>";
		 }
		 else{
			for($i=1;$i<=$count;$i++){
				$content .= "<span class='page-number";
				if($i==1){
					$content .= " active";
				}
				$content .= "' id='destination-page-number-".$i."' style='cursor:pointer;' onclick='gotoblock(\"".$i."\",\"destination\")'>".$i."</span>";
			}	
		 }
			
		$content .= "</div>";
		
		foreach($results as $key=>$result){
			$num = $key+1;
			$node =  node_load($result->nid);
			//print '<pre>';
			//print_r($node);
			$image_uri = $node->field_destination_image['und'][0]['uri'];
			$image = file_create_url($image_uri);
			$destination_name = $node->node_title;
			$price = $result->node_data_field_destination_show_homepage_field_destination_price_value;
			$body = $node->body['und'][0]['value'];
			
			$destination_id = 'node/'.$result->nid;
			$path = drupal_get_path_alias($destination_id);

			$content .= "<div id='destination-".$num."'";
			if($num!=1){
					$content .= "style='display:none;'";
			}
			$content .=">";
			$content .= "<div class='destination-inner'>";
			$content .= "<div class='destination-content-image'><img src='".$image."' alt='img-destination' width='272' height='145'></div>";
			$content .= "<div class='destination-content-title'>".$destination_name."</div>";
			$content .= "<div class='destination-content-body'>".$body."</div>";
			$content .= "</div>";
			//$content .= "<div class='destination-content-readmore'><a href='/destinations' onmouseover=\"document.dest_readmore.src='/sites/all/themes/stu/images/bt_readmoreOver.jpg'\" onmouseout=\"document.dest_readmore.src='/sites/all/themes/stu/images/bt_readmore.jpg'\"><img src='/sites/all/themes/stu/images/bt_readmore.jpg' name='dest_readmore' alt='readmore-destination'></a></div>";		
			$content .= "<div class='destination-content-readmore'><a href='".$path."' \">Find out more +</a></div>";		
			$content .= "</div>";
		}
	}else{
		$content .= "<div>&nbsp;</div>";	
	}	
	$content .= "</div>";
	$content .= "</div>";
	return $content;
}

function makeover_homepage_packages(){
	$results = views_get_view_result('home_packages', null);
	$count = count($results);		
	
	$content = "<div id='home-packages'>";
	$content .= "<div id='packages-content'>";
	if($count){
		$content .= "<div class='packages-content-page'>";
		for($i=1;$i<=$count;$i++){
			$content .= "<span class='page-number";
			if($i==1){
				$content .= " active";
			}
			$content .= "' id='packages-page-number-".$i."' style='cursor:pointer;' onclick='gotoblock(\"".$i."\",\"packages\")'>".$i."</span>";
		}	
		$content .= "</div>";	

		foreach($results as $key=>$result){
		
			$num = $key+1;
			$node =  node_load($result->nid);
			//print '<pre>';
			//print_r($node);
			$image_uri = $node->field_package_image['und'][0]['uri'];
			$image = file_create_url($image_uri);
			$package_name = $result->node_title;
			$price = $node->field_package_price['und']['0']['value'];
			$body = $node->body['und']['0']['value'];
			
			$package_id = 'node/'.$result->nid;
			$path = drupal_get_path_alias($package_id);

			$content .= "<div id='packages-".$num."'";
			if($num!=1){
					$content .= "style='display:none;'";
			}
			$content .=">";
				$content .= "<div class='package-inner'>";
				$content .= "<div class='packages-content-image'><img src='".$image."' alt='img-package' width='272' height='145'></div>";
				$content .= "<div class='packages-content-title'>".$package_name."</div>";
				$content .= "<div class='packages-content-price'>From  NZ $".$price."</div>";
				$content .= "<div class='packages-content-body'>".$body."</div>";
				//$content .= "<div class='packages-content-readmore'><a href='".$path."' onmouseover=\"document.package_readmore_".$num.".src='/sites/all/themes/stu/images/bt_readmoreOver.jpg'\" onmouseout=\"document.package_readmore_".$num.".src='/sites/all/themes/stu/images/bt_readmore.jpg'\"><img src='/sites/all/themes/stu/images/bt_readmore.jpg' name='package_readmore_".$num."' alt='readmore-package'></a></div>";		
				$content .= "</div>";
				$content .= "<div class='packages-content-readmore'><a href='".$path."' \">Find out more +</a></div>";		
				
			$content .= "</div>";
		}		
	}else{
		$content .= "<div>&nbsp;</div>";	
	}	
	$content .= "</div>";
	$content .= "</div>";
	return $content;
}

function markup_homepage_testimonials(){
	global $base_url;
	$results = views_get_view_result('home_testimonials', null);
	$count = count($results);		
	
	$content = "<div id='home-testimonials'>";
	$content .= "<div id='testimonials-content'>";
	if($count){
	
		//Page
		$content .= "<div class='testimonials-content-page'>";
		 for($i=1;$i<=$count;$i++){
			 $content .= "<span class='page-number";
			 if($i==1){
				 $content .= " active";
			 }
			 $content .= "' id='testimonials-page-number-".$i."' style='cursor:pointer;' onclick='gotoblock(\"".$i."\",\"testimonials\")' >".$i."</span>";
		 }	
		 $content .= "</div>";
		
		$content .= "<div class='contentWrap'>";
		//$count_limit = 0;
		
		foreach($results as $key=>$result){	
			//echo '<pre>';
			//print_r($result);
			$num = $key+1;
			$name = $result->_field_data['nid']['entity']->field_testimonial_patient_name['und'][0]['value'];
			
			$location = $result->_field_data['nid']['entity']->field_testimonial_location['und'][0]['value'];
			$body = $result->_field_data['nid']['entity']->body['und'][0]['value'];
			$procedure = $result->node_field_data_field_testimonial_procedures_title;
			
			$procedure_id = 'node/'.$result->_field_data['nid']['entity']->field_testimonial_procedures['und'][0]['nid'];
			$path = drupal_get_path_alias($procedure_id);
			
			$doctor_id = 'node/'.$result->_field_data['nid']['entity']->field_testimonial_doctor['und'][0]['nid'];
			$path_doctor = drupal_get_path_alias($doctor_id);
			$node = node_load($result->node_data_field_testimonial_patient_name_field_testimonial_doctor_nid);
			$doctor_name = $node->title;
			
			$nid = $result->nid;
			
			 $content .= "<div id='testimonials-".$num."'";			
			 if($num!=1){
					$content .= "style='display:none;'";
			 }
			 $content .=">";
			
			if($count_limit < 10){
				//if($procedure){
					$content .="<div class='content-testimonial'>";
						$content .= "<div class='testimonials-inner'>";
						
						$content .= "<div class='testimonials-content-procedure'>";
						
						$content .= "<div class='testimonials-content-title'>";
						$content .= "<div class='testimonials-name'>".$name."</div>";
						$content .= "<div class='testimonials-localtion'>".$location."</div>";
						$content .= "</div>";
						$content .= "<div class='testimonials-procedure-link'>";
						if($procedure){
						$content .= "<a href='".$path."'>".$procedure."</a>";
						}
						$content .= "</div>";
						
					  $content .="</div>";
						$content .="<div class='testimonials-comment'>";
						$content .= "	<div class='home-quote-open'><img src='". $base_url ."/sites/all/themes/stu/images/quote1-white.png'></div>";
						//$content .= "	<div class='testimonials-content-body'>".truncate($body,450,'...')."</div>";
						$content .= "	<div class='testimonials-content-body'><a href='/whatclientssay/written#T".$nid."'>".makeover_trim_text($body,250)."</a></div>";
						$content .= "	<div class='clear-block'></div>";
						$content .="</div>";
						$content .= "<div class='procedure-testimonial-longbody' style='display: none;'></div>";
						$content .= "<div class='home-quote-close'><img src='". $base_url ."/sites/all/themes/stu/images/quote2-white.png'></div>";
						$content .= "</div><!-- end-testimonials-inner-->";
			
						
					
					$content .= "</div>";
					//$count_limit++;
				//}
			}
			$content .= "</div>";
		}
		
	}else{
		$content .= "<div>&nbsp;</div>";	
	}
	$content .= "</div>";	
	$content .= "<div class='testimonials-content-readmore'>".l('View all testimonials','node/28')."</div>";
	$content .= "</div>";
	$content .= "</div>";
	return $content;
}

function makeover_truncate($string, $max = 20, $rep = '')
{
    if (strlen($string) <= ($max + strlen($rep)))
    {
        return $string;
    }
    $leave = $max - strlen ($rep);
    return substr_replace($string, $rep, $leave);
}

function makeover_trim_text($text,$max_lenght){
  $alter = array(
	  'max_length' => $max_lenght,
	   'ellipsis' => TRUE,
	  'html' => TRUE,
	  'word_boundary' => TRUE
	);
	return views_trim_text($alter, $text);
}

function makeover_pricelist_block() {
	$output = theme('stu_pricelist');
	return   $output;  
}

function makeover_procedurelist_block() {
	$output = theme('stu_procedurelist');
	return   $output;  
}

function makeover_video_block() {
	$output = theme('stu_video');
	return $output;  
}

/**
 * Get Staff users email ids
 */
function _makeover_get_staff_user() {
	$emails = '';
	$query = db_select('users','u');
	$query->join('users_roles', 'r', 'u.uid = r.uid AND r.rid = :rid', array(':rid' => 4));
	$query-> fields('u',array('mail'));
	
	$result= $query->execute();
  foreach($result as $record){
	  $mails[] = $record->mail;
	}  
	if (sizeof($mails) > 0) {
	  $emails = implode($mails,', ');	
	} 
	return $emails;
}
