<?php
module_load_include('inc', 'stu_forms', 'includes/quote.pages');

/**
 * Implementing hook_init()
 */
function stu_forms_init() {
  global $user;
  $arg = arg();
	 drupal_add_library('system', 'ui.accordion');
	 if (isset($_GET['rate']) && !empty($_GET['rate'])) {
		 $_SESSION['CRATE'] =  variable_get($_GET['rate'], '');
		 $_SESSION['CURR'] =  $_GET['rate'];
	 }
	 else {
	   $_SESSION['CRATE'] =  variable_get('THB', '');
		 $_SESSION['CURR'] =  'THB'; 
	 }
   	
	 if ((arg(0) == 'node') && !($user->uid)) {
	   $node = node_load(arg(1));
	   if ($node->type == 'surgeon' || $node->type == 'quote') {
	     drupal_access_denied();
	     exit();
	     }
	 }
	if (arg(0) == 'taxonomy' && arg(1) == 'term' && $user->uid != 1) {
    drupal_access_denied();
	  exit();
  }
  if ($arg[0] == 'node' && sizeof($arg) == 1) {
    drupal_access_denied();
	  exit();
  }
}
 
 
/**
 * Implementing hook_menu()
 */
function stu_forms_menu() {
	$items['admin/makeover/settings/surgeon'] = array(
		'title'=>'Surgeon Form Settings',
		'page callback'=>'drupal_get_form',
		'page arguments' => array('surgeon_admin_settings'),
	  'access arguments' => array('makeover admin access'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'includes/stu_forms.admin.inc',
	);
	// Admin settings for mail template
	$items['admin/makeover/settings/get-quote-surgery'] = array(
		'title'=>'Get A Quote Surgery with or without Dental Template',
		'page callback'=>'drupal_get_form',
		'page arguments' => array('get_quote_surgery_admin_settings'),
	  'access arguments' => array('makeover admin access'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'includes/quote.admin.inc',
	);
	$items['admin/makeover/settings/get-quote-dental'] = array(
		'title'=>'Get A Quote Dental Template',
		'page callback'=>'drupal_get_form',
		'page arguments' => array('get_quote_dental_admin_settings'),
	  'access arguments' => array('makeover admin access'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'includes/quote.admin.inc',
	);
	$items['admin/makeover/settings/get-quote-hair'] = array(
		'title'=>'Get A Quote Hair Template',
		'page callback'=>'drupal_get_form',
		'page arguments' => array('get_quote_hair_admin_settings'),
	  'access arguments' => array('makeover admin access'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'includes/quote.admin.inc',
	);
	$items['admin/makeover/settings/notify-quote'] = array(
		'title'=>'Send Quote Notification',
		'page callback'=>'drupal_get_form',
		'page arguments' => array('send_quote_notification'),
	  'access arguments' => array('makeover admin access'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'includes/quote.admin.inc',
	);
	$items['admin/makeover/settings/currency'] = array(
		'title'=>'Currency Rate Setting',
		'page callback'=>'drupal_get_form',
		'page arguments' => array('get_quote_currency_rate_admin_settings'),
	  'access arguments' => array('makeover admin access'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'includes/quote.admin.inc',
	);
	$items['admin/makeover/settings/notify-quote-staff'] = array(
		'title'=>'Send Quote Notification To Staff',
		'page callback'=>'drupal_get_form',
		'page arguments' => array('send_quote_notification_staff'),
	  'access arguments' => array('makeover admin access'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'includes/quote.admin.inc',
	);
  $items['admin/makeover/settings/insightly_integration_for_drupal'] = array(
    'title' => 'Insightly Integration for Drupal',
    'description' => 'Configuration for Insightly Integration for Drupal module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_my_insightly_integration_for_drupal_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
	$items['getquote'] = array(
		'title'=>'Get A Quote',
		'page callback'=>'drupal_get_form',
		'page arguments' => array('getquote'),
	  'access arguments' => array('content access'),
		'file' => 'includes/quote.admin.inc',
	);
	$items['thankyou/%'] = array(
		'title'=>'Thank You',
		'page callback'=>'_thank_you_page',
		'page arguments' => array(1),
	  'access arguments' => array('access content'),
		'file' => 'includes/quote.pages.inc',
	);
	return $items;
}
	

/**
 * Implementing hook_theme()
 */
function stu_forms_theme($existing, $type, $theme, $path) {
  $path = drupal_get_path('module', 'stu_forms') .'/templates';
	return array(
	  'surgeon_pdf' => array(
		  'variables' => array('node' => NULL,'print_logo' => NULL),
		  'template' => 'surgeon--pdf',
		  'path' => $path
		),
    'dental_pdf' => array(
		  'variables' => array('node' => NULL,'print_logo' => NULL),
		  'template' => 'dental--pdf',
		  'path' => $path
		),
		'quote_node_form' => array(
		  'render element' => 'form',
		  'template' => 'node-form-quote',
		  'path' => drupal_get_path('theme', 'smo').'/templates'
		),
		'quote_surgery_estimate' => array(
		  'variables' => array('hotalPrice' => NULL, 'exchangeRate' => NULL, 'surgeryEstimate' => NULL, 'dentalEstimate' => NULL, 'currency' => NULL),
		  'template' => 'quote--surgery--estimate',
		  'path' => $path
		),
		'quote_hair_estimate' => array(
		  'variables' => array('hotalPrice' => NULL, 'exchangeRate' => NULL, 'hairTransplants' => NULL,'currency' => NULL),
		  'template' => 'quote--hair--estimate',
		  'path' => $path
		),
		'quote_dental_estimate' => array(
		  'variables' => array('hotalPrice' => NULL, 'exchangeRate' => NULL, 'dentalEstimate' => NULL,'currency' => NULL),
		  'template' => 'quote--dental--estimate',
		  'path' => $path
		),		
  ); 
}

/**
 *  Implementing hook_form_alter()
 */
function stu_forms_form_alter(&$form, &$form_state, $form_id) {
	global $user;
	if ($form_id == 'surgeon_node_form' || $form_id == 'quote_node_form') {
		$form["field_sg_title"][LANGUAGE_NONE]['#options']['_none'] = t('- Select -');
		$form["field_sg_countries"][LANGUAGE_NONE]['#options']['_none'] = t('- Please Select -');
		$form["field_sg_prefer_contact"][LANGUAGE_NONE]['#options']['_none'] = t('- Please Select -');
		$form["field_surgery_location"][LANGUAGE_NONE]['#options']['_none'] = t('- Please Select -');
		$form["field_preferred_currency"][LANGUAGE_NONE]['#options']['_none'] = t('- Please Select -');
		$form["field_hear_about_us"][LANGUAGE_NONE]['#options']['_none'] = t('- Please Select -');
		
		// Get a fully loaded entity object for the logged in user.
    $account = user_load($GLOBALS['user']->uid);
    
    if ($account && empty($form['nid']['#value'])) {
			$form["title"]['#default_value'] = $user->mail;
	  }
	 // Removed Required
		$form["title"]['#required'] = false;
		drupal_add_css(drupal_get_path('theme', 'smo').'/css/surgeon-form.css');
		$form['#after_build'][] = 'stu_forms_surgeon_afterbuild';
		
		if ($form_id == 'surgeon_node_form') {
      $form['#after_build'][] = 'stu_forms_surgeonformonly_afterbuild';
			// Change title
			drupal_set_title('Opinion Form');
			$form['field_sg_preferred_surgeon'][LANGUAGE_NONE][0]['value']['#title'] = t('Preferred Surgeon') . ' (' .l(t('Click Here for Surgeons'),'node/29', array('attributes' => array('class' => 'preferred_surgeon','target' => '_blank'))).')';
			$form['field_sg_wm_milk'][LANGUAGE_NONE]['#title'] = t('Do your breasts still have milk at this time? NOTE: Lactation may also be induced by other factors such as hormone intake. Please test by squeezing breasts.');
			$form['actions']['submit']['#submit'][] = 'stu_form_surgeon_customform_submit';
			$form['actions']['submit']['#value'] = t('Click here to MAKE YOUR DREAMS COME TRUE');
			$form['#validate'][] = 'stu_form_customform_validate';
      
      // Added Maxlength
      $form['field_sg_procedures'][LANGUAGE_NONE][0]['value']['#maxlength'] = 160;
      $form['field_sg_heart_disease_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 160;
      $form['field_sg_diabetes_new_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 160;
      $form['field_sg_hypertension_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 160;
      $form['field_sg_asthma_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 160;
      $form['field_sg_cancer_new_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 160;
      $form['field_sg_diabetes_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_sg_thyroid_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_sg_heart_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_sg_lung_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_sg_blood_pressure_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_sg_liver_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_sg_blood_disorder_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_sg_cancer_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_sg_hiv_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_sg_depression_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_sg_neurologic_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_sg_anaesthesia_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_cardiovascular_acc_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_bleeding_tendency_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_hyperthyroidism_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_adrenal_insufficiency_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_hepatitus_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_hiv_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_keloid_scarring_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_breast_cancer_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_major_operation_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_underlying_disease_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      $form['field_treated_info'][LANGUAGE_NONE][0]['value']['#maxlength'] = 120;
      
      // attach js file in from callback
      $form['#attached']['js'] = array(
        drupal_get_path('module', 'stu_forms') . '/js/stu_forms.js',
      );
      if (empty($form['nid']['#value'])) {
        $form["field_treatment_type"][LANGUAGE_NONE]['#default_value'] = (arg(3)) ? ucwords(arg(3)) : 'Surgery';
      }
     
      
      $arg = arg();
      $groups = $form['#groups'];
      //$form["field_dental_images"]['#access'] = 0;
      if (empty($form['nid']['#value'])) {
        if($arg[3] == 'both') {
          $form["field_dental_images"]['#access'] = 1;
          $form["field_dental_plan_date"]['#access'] = 0;
          $form["field_dental_homedate"]['#access'] = 0;
          $form['field_dental_medicine']['#access'] = 0;
          $form['field_dental_supplements']['#access'] = 0;
          $form['field_dental_medical_conditions']['#access'] = 0;
          $form['field_dental_medications']['#access'] = 0;
          $form['field_dental_vitamins']['#access'] = 0;
        } 
        else if($arg[3] == 'dental') {
          $form["field_dental_images"]['#access'] = 1;
          $form["field_sg_height"]['#access'] = 0;
          $form["field_sg_weight"]['#access'] = 0;
          $form["field_sg_preferred_language"]['#access'] = 0;
          unset($groups['group_general']);
          unset($groups['group_dental_detail']);
          unset($groups['group_dental_medicines_condition']);
          unset($groups['group_dental_health']);
          unset($groups['group_dental_medical_history']);
          foreach ($groups as $group) {
            foreach ($group->children as $field) {
              $form[$field]['#access'] = 0;
            }
          }
          field_group_hide_field_groups($form, 
              array(
                'group_medical_history',
                'group_breast_surgery_details',
                'group_medical_conditions',
                'group_family_medical_conditions',
                'group_medical_history',
                'group_women_surgery',
                'group_medical_conditions',
                'group_surgery_details',
                'group_women',
                'group_dental_images',
              )
            );
        }
        else if (count($arg) == 3 || $arg[3] == 'surgery') {
          $form['field_dental_plan_date']['#access'] = 0;
          $form['field_dental_homedate']['#access'] = 0;
          $form['field_dental_procedure']['#access'] = 0;
          $form['field_dental_expectation']['#access'] = 0;
          $form['field_dental_questions']['#access'] = 0;
          $form['field_dental_medicine']['#access'] = 0;
          $form['field_dental_supplements']['#access'] = 0;
          $form['field_dental_medical_conditions']['#access'] = 0;
          $form['field_dental_health']['#access'] = 0;
          //$form["field_dental_images"]['#access'] = 0;
          $form["field_dental_health_text"]['#access'] = 0;
          $form["field_dental_concerns"]['#access'] = 0;
          $form['field_dental_medications']['#access'] = 0;
          $form['field_dental_vitamins']['#access'] = 0;
          field_group_hide_field_groups($form, 
            array(
              'group_dental_detail',
              'group_dental_medicines_condition',
              'group_dental_health',
              'group_dental_medical_history',
              'group_dental_images',
            )
          );
        }
      }
      else {
       $treatment_type = $form['#node']->field_treatment_type[LANGUAGE_NONE][0]['value'];
       if (isset($treatment_type) && !empty($treatment_type) && in_array('other_user', array_values($user->roles))) {
          $form['field_treatment_type']['#access'] = 0;
          if ($treatment_type == 'Dental') {
            $form["field_dental_images"]['#access'] = 0;
            $form["field_sg_height"]['#access'] = 0;
            $form["field_sg_weight"]['#access'] = 0;
            $form["field_sg_preferred_language"]['#access'] = 0;
            field_group_hide_field_groups($form, 
              array(
                'group_medical_history',
                'group_breast_surgery_details',
                'group_medical_conditions',
                'group_family_medical_conditions',
                'group_medical_history',
                'group_women_surgery',
                'group_medical_conditions',
                'group_surgery_details',
                'group_women',
                'group_dental_images',
              )
            );
          }
          else if ($treatment_type == 'Surgery') {
            field_group_hide_field_groups($form, 
              array(
                'group_dental_detail',
                'group_dental_medicines_condition',
                'group_dental_health',
                'group_dental_medical_history',
                'group_dental_images',
              )
            );
          }
        }  
      }
		}
		if ($form_id == 'quote_node_form') {
       // Hide option THB
       if (empty($form['nid']['#value'])) {
           unset($form["field_preferred_currency"][LANGUAGE_NONE]['#options']['THB']);
        }	
	
        	// Change title
			drupal_set_title('Free Estimate');
			$node = $form['#node'];
      $form['field_expect_from_surgery'][LANGUAGE_NONE][0]['value']['#title'] = $form['field_expect_from_surgery'][LANGUAGE_NONE][0]['#title']. ' <span>('.$form['field_expect_from_surgery'][LANGUAGE_NONE][0]['#description'].')</span>';
		  $form['actions']['submit']['#value'] = t('Click here to MAKE YOUR DREAMS COME TRUE');
	    $form['actions']['submit']['#submit'][] = 'stu_form_quote_customform_submit';
	    $form['#validate'][] = 'stu_form_customform_quote_validate';
    }
  }
  if ($form_id == 'contact_site_form') {
		// Change title
		drupal_set_title('Contact Us');
	}
}

/**
 * Get Hotals
 */
function _custom_get_hotels($location_nid){
  $output = array('_none' => '- None -');
  $query = db_select('field_data_field_hotal_cost','hotal');
	$query->join('field_data_field_hotal_city','city','hotal.entity_id = city.entity_id');
	$query->join('taxonomy_term_data','term','hotal.entity_id = term.tid');
	$query->fields('term',array('name','tid'));
	$query->condition('hotal.bundle', 'accommodation', '=');
	$query->condition('hotal.entity_type', 'taxonomy_term', '=');
	$query->condition('city.field_hotal_city_nid', $location_nid , '=');
	$results = $query->execute()->fetchAll();
	foreach ($results as $result) {
	  $output[$result->tid] = $result->name;
	}
	return $output;
}

/**
 * Ajax Callback
 */
function ajax_surgery_location_callback($form, $form_state) {
	return $form['field_accommodation'];
}


/**
 * Submit handler of surgeon_form
 * After form submit if this is new user then we create new user account.
 */
function stu_forms_surgeonformonly_afterbuild($form, &$form_state) {
  global $user;
  // Change title
  drupal_set_title('Opinion Form');
  if(in_array('administrator', array_values($user->roles)) || in_array('stu_staff', array_values($user->roles))){
    // Remove validation when admin is creating user.
    $form["field_sg_email"][LANGUAGE_NONE][0]['email']['#required'] = false;
    foreach (element_children($form) as $key) {
      if (strpos($key, 'field_') !== FALSE) {
        $form[$key][LANGUAGE_NONE][0]['value']['#required'] = FALSE;
        $form[$key][LANGUAGE_NONE]['#required'] = FALSE;
      }
    }
  }
	return $form;
}

/**
 * Submit handler of surgeon_form
 * After form submit if this is new user then we create new user account.
 */
function stu_forms_surgeon_afterbuild($form, &$form_state) {
	drupal_add_css(drupal_get_path('theme', 'smo').'/css/surgeon-form.css');
	// Removed Required
	$form["title"]['#required'] = false;
	if ($form["field_sg_email"][LANGUAGE_NONE][0]['email']['#default_value']) {
	  $form["title"]['#default_value'] = $form["field_sg_email"][LANGUAGE_NONE][0]['email']['#default_value'];
	}
  return $form;
}

  
/**
 * Validate handler of QUOTE_form
 * After form submit if this is new user then we create new user account.
 */
function stu_form_customform_validate($form, &$form_state) {
	global $user;
  $values = $form_state['values'];
	if(empty($values[nid]) && user_is_anonymous()) {
		$email = $values['field_sg_email'][LANGUAGE_NONE][0][email];
		$uid = db_query("SELECT uid FROM {users} WHERE mail = :mail", array(':mail' => $email))->fetchField();
		if ($uid) {
			$_SESSION['OPINIONAL_AUTHOR'] = $uid;
			//form_set_error('field_sg_email', t('Another user already exists in the system with the same email address.'));	
		}
	}
	if ($form_state['values']['field_sg_email'][LANGUAGE_NONE][0][email] != $form_state['values']['field_sg_phone'][LANGUAGE_NONE][0][value]) {
    form_set_error('field_sg_phone', 'The email address must match with confirm email.');
  }
}


/**
 * Validate handler of QUOTE_form
 * After form submit if this is new user then we create new user account.
 */
function stu_form_customform_quote_validate($form, &$form_state) {
	global $user;
  $values = $form_state['values'];
	if(empty($values[nid]) && user_is_anonymous()) {
		$email = $values['field_sg_email'][LANGUAGE_NONE][0][email];
		$uid = db_query("SELECT uid FROM {users} WHERE mail = :mail", array(':mail' => $email))->fetchField();
		if ($uid) {
			$_SESSION['OPINIONAL_AUTHOR'] = $uid;
			//form_set_error('field_sg_email', t('Another user already exists in the system with the same email address.'));	
		}
	}
	if (filter_var($values['field_sg_email'][LANGUAGE_NONE][0][email], FILTER_VALIDATE_EMAIL) == false) {
		form_set_error('field_sg_email', t('Please enter valid email address.'));
	}
	
  if (strcmp($values['field_sg_email'][LANGUAGE_NONE][0][email], $values['field_confirm_email_address'][LANGUAGE_NONE][0][email]) !== 0) {
		form_set_error('field_confirm_email_address', t('Email address does not not match.'));
	}
}



/**
 * Submit handler of QUOTE_form
 * After form submit if this is new user then we create new user account.
 */
function stu_form_quote_customform_submit($form, &$form_state) {
	global $user;
  $values = $form_state['values'];
	$password = user_password(8);
	//if(empty($values[nid]) && user_is_anonymous()) {
	if(user_is_anonymous()) {
		$email = $values['field_sg_email'][LANGUAGE_NONE][0][email];
		
		$query = db_select('users', 'u');
    $query->fields('u', array('uid'));
    $query->condition('u.mail', $email);
    $row_count = $query->countQuery()->execute()->fetchField();

		//$uid = db_query("SELECT uid FROM {users} WHERE mail = :mail", array(':mail' => $email))->fetchField();
		if ($row_count == 0) {
			if (!user_load_by_mail($email)) {
				
				// User doesn't exist, Save the user.
        $emailname = substr($email, 0, strpos($email, '@'));
				$emailname = str_replace('+','',$emailname);
				$new_user = array(
					'name' => $email,
					'pass' => $password,  // Fixed issue
					'mail' => $values['field_sg_email'][LANGUAGE_NONE][0][email],
					'signature_format' => 'full_html',
					'status' => 0,
					'language' => 'en',
					'init' => $values['field_sg_email'][LANGUAGE_NONE][0][email],
					'roles' => array(
						DRUPAL_AUTHENTICATED_RID => 'authenticated user',
					),
					'field_sg_title' => array(
						'und' => array(
							0 => array(
								'value' => $values['field_sg_title'][LANGUAGE_NONE][0][value]
							),
						),
					),
					'field_sg_first_name' => array(
						'und' => array(
							0 => array(
								'value' => $values['field_sg_first_name'][LANGUAGE_NONE][0][value]
							),
						),
					),
					'field_sg_last_name' => array(
						'und' => array(
							0 => array(
								'value' => $values['field_sg_last_name'][LANGUAGE_NONE][0][value]
							),
						),
					),
					'field_sg_city' => array(
						'und' => array(
							0 => array(
								'value' => $values['field_sg_city'][LANGUAGE_NONE][0][value]
							),
						),
					),
					'field_sg_passport_number' => array(
						'und' => array(
							0 => array(
								'value' => $values['field_sg_daytime_phone_number'][LANGUAGE_NONE][0][value]
							),
						),
					),
					'field_sg_passport_number' => array(
						'und' => array(
							0 => array(
								'value' => $values['field_sg_evening_phone_number'][LANGUAGE_NONE][0][value]
							),
						),
					),
					'field_sg_phone' => array(
						'und' => array(
							0 => array(
								'value' => $values['field_sg_phone'][LANGUAGE_NONE][0][value]
							),
						),
					),
					'field_sg_countries' => array(
						'und' => array(
							0 => array(
								'value' => $values['field_sg_countries'][LANGUAGE_NONE][0][value]
							),
						),
					),
					'field_sg_postal_street_address' => array(
						'und' => array(
							0 => array(
								'value' => $values['field_sg_postal_street_address'][LANGUAGE_NONE][0][value]
							),
						),
					),
					'field_sg_postcode_zip' => array(
						'und' => array(
							0 => array(
								'value' => $values['field_sg_postcode_zip'][LANGUAGE_NONE][0][value]
							),
						),
					),
					'field_sg_region_state' => array(
						'und' => array(
							0 => array(
								'value' => $values['field_sg_region_state'][LANGUAGE_NONE][0][value]
							),
						),
					),
					'field_sg_suburb' => array(
						'und' => array(
							0 => array(
								'value' => $values['field_sg_suburb'][LANGUAGE_NONE][0][value]
							),
						),
					),
			 );
			 $account = user_save(NULL, $new_user);
			 $_SESSION['OPINIONAL_AUTHOR'] = $account->uid;
			 $op = 'register_pending_approval';
			 //$status = _user_mail_notify($op, $account);
			}	
		}
	}
	
	/******* Price Calculation ************/
  $location_nid = $form_state['values']['field_surgery_location'][LANGUAGE_NONE][0][nid]; 
  
  // Get Hotal for 1 day
	if ($location_nid) {
		$query = db_select('node','n');
		$query->fields('n',array('title'));
		$query->condition('n.type', 'destinations', '=');
		$query->condition('n.nid', $location_nid, '=');
		$location = $query->execute()->fetchField();
	}
	
	$surgeries = $form_state['values']['field_surgical_procedures'][LANGUAGE_NONE];
	$preferred_currency = $form_state['values']['field_preferred_currency'][LANGUAGE_NONE][0][value];
	$dentals = $form_state['values']['field_dental_procedures'][LANGUAGE_NONE];
	$hairTransplants = $form_state['values']['field_hairtransplant_procedures'][LANGUAGE_NONE];
	
	$hotal = $form_state['values']['field_accommodation'][LANGUAGE_NONE][0][tid];
	$preferred_currency = $form_state['values']['field_preferred_currency'][LANGUAGE_NONE][0][value];
	
	// The easiest way to determine if a surgery requires the $400 booking fee or
  // the $200 out patient booking fee is based on the total cost of surgery. If
  // the total surgery cost is less than THB51,000 then the $200 applies.
	
	// Exchange Rate
	$exchangeRate = 1;
	if ($preferred_currency) { 
	  //$exchangeRate = era_rate('THB', $preferred_currency); // FROM -> TO
	  $exchangeRate = variable_get($preferred_currency, ''); // FROM -> TO
	  $currency_symbol = _currency_symbol();
	  $_SESSION['CURRENCY_SYMBOL'] = $currency_symbol[$preferred_currency]; 
	  $_SESSION['CURRENCY'] = $preferred_currency;
	}
	 
	 // Get all hotel cost
	 $hotal_cost = array();
	 $query = db_select('field_data_field_hotal_cost','hotal');
	 $query->join('field_data_field_hotal_city','city','hotal.entity_id = city.entity_id');
	 $query->fields('hotal',array('field_hotal_cost_value'));
	 $query->fields('city',array('field_hotal_city_nid'));
	 $query->condition('hotal.bundle', 'accommodation', '=');
	 $query->condition('hotal.entity_type', 'taxonomy_term', '=');
	 $results = $query->execute()->fetchAll();
	 if (sizeof($results)) {
	  foreach ($results as $result) {
		  $hotal_cost[$result->field_hotal_city_nid] = 	$result->field_hotal_cost_value;
		}	 
	}
	
	// Get All Destination
	 $destinations = array();
	 $query = db_select('node','node');
	 $query->fields('node',array('nid','title'));
	 $query->condition('node.type', 'destinations', '=');
	 $query->condition('node.status', 1, '=');
	 $results = $query->execute()->fetchAll();
	 if (sizeof($results)) {
	  foreach ($results as $result) {
		  $destinations[$result->nid] = 	$result->title;
		}	 
	}
	
	/******* Price Calculation ************/
	
  /******** Send mail ********/
  $dental_cost = '';
   if ((sizeof($dentals) > 0) && empty($surgeries)) { // Estimate for Dental only
		  $dental_cost = _getDentalPriceByLocation($dentals, $destinations);
		  _sendmail_quote_dental_estimate($form_state['values'], $hotal_cost, $exchangeRate, $dental_cost, $preferred_currency);
	 }
	 else if (sizeof($surgeries) > 0) { // Estimate for Surgery with or without Dental
		  if (sizeof($dentals) > 0) {
		     $dental_cost = _getDentalPriceByLocation($dentals, $destinations);
		  }
		   $surgery_cost = _getSurgeryPriceByLocation($surgeries, $destinations);
		   _sendmail_quote_surgery_estimate($form_state['values'], $hotal_cost, $exchangeRate, $surgery_cost, $dental_cost, $preferred_currency);
	 }
	 // Hair Transplant
	 if (sizeof($hairTransplants) > 0) {
		 $hairTransplants_cost = _getHairTransplantPriceByLocation($hairTransplants, $destinations);
		 _sendmail_quote_hair_transplant_estimate($form_state['values'], $hotal_cost, $exchangeRate, $hairTransplants_cost, $preferred_currency);
	 }
  
  /********* Sned Mail ******/
  $form_state['redirect'] = 'thankyou/quote';
}


/**
 * Submit handler of surgeon_form
 * After form submit if this is new user then we create new user account.
 */
function stu_form_surgeon_customform_submit($form, &$form_state) {
  $form_state['redirect'] = 'thankyou/surgeon';
}


/**
 *  Implementing hook_node_presave()
 */
function stu_forms_node_presave($node) {
	if (($node->type == 'surgeon' || $node->type == 'quote') && $node->is_new) {
		$node->title = strtolower($node->field_sg_email[LANGUAGE_NONE][0][email]);
    $node->field_ip_address[LANGUAGE_NONE][0][value]  = ip_address();
    
		if ($_SESSION['OPINIONAL_AUTHOR']) {
		  $node->uid = $_SESSION['OPINIONAL_AUTHOR'];	
		}
		unset($_SESSION['OPINIONAL_AUTHOR']);
	}
}

/**
 *  Implementing hook_node_presave()
 */
function stu_forms_node_insert($node) {
	if ($node->type == 'surgeon') {
    $treatment_type = field_get_items('node', $node, 'field_treatment_type');
    
    $field_term_condition = field_get_items('node', $node, 'field_term_condition');
    $field_term_condition = $field_term_condition[0]['value'];
    
    if ($field_term_condition) {
      if ($treatment_type) {
        $treatment_type = $treatment_type[0]['value'];
        
        if ($treatment_type != 'Surgery') {
          _customDentalPdf($node);
        }
        
        if ($treatment_type != 'Dental') {
          _customGeneratePdf($node);
        }
        
        if ($treatment_type == 'Dental') {
          _stu_forms_send_dental($node->nid);
        }
        else {
          _stu_forms_send_surgeon($node->nid);
        }
      }
    }
  }
	else if ($node->type == 'quote') {
	   _sendmail_quote_estimate_notification_staff($node);
     _sendDataToCRM($node);	
	}
}

/**
 *  Implementing hook_node_presave()
 */
function stu_forms_node_update($node) {
	if ($node->type == 'surgeon') {
    $treatment_type = field_get_items('node', $node, 'field_treatment_type');
    
    $field_term_condition = field_get_items('node', $node, 'field_term_condition');
    $field_term_condition = $field_term_condition[0]['value'];
    
    if ($field_term_condition) {
      if ($treatment_type) {
        $treatment_type = $treatment_type[0]['value'];
        
        if ($treatment_type != 'Surgery') {
          _customDentalPdf($node);
        }
        
        if ($treatment_type != 'Dental') {
          _customGeneratePdf($node);
        }
        
        if ($treatment_type == 'Dental') {
          _stu_forms_send_dental($node->nid);
        }
        else {
          _stu_forms_send_surgeon($node->nid);
        }
      }
      
      if ($treatment_type != 'Dental') {
        _customGeneratePdf($node);
      }
      
      if ($treatment_type == 'Dental') {
        _stu_forms_send_dental($node->nid);
      }
      else {
        _stu_forms_send_surgeon($node->nid);
      }
    }
    
  }
}

/**
 * Attach pdf & send mail
 */
function _stu_forms_send_surgeon($nid) {
  global $base_url, $user;
  require_once(libraries_get_path('phpmailer') . '/class.phpmailer.php');
  $language = language_default();
  
  $node = node_load($nid, NULL, TRUE);
  
  $subject = 'Opinion Form by '. $node->title;
  $msg = 'See Attached.';
  $surgeon_staff = variable_get('surgeon_staff', '');
  $from = variable_get('site_mail', '');
  
  $field_sg_email = field_get_items('node', $node, 'field_sg_email');
  $field_sg_email = $field_sg_email[0]['email'];
  
  $field_sg_first_name = field_get_items('node', $node, 'field_sg_first_name');
  $field_sg_first_name = $field_sg_first_name[0]['value'];
  $name[] = ucwords($field_sg_first_name);
  
  $field_sg_last_name = field_get_items('node', $node, 'field_sg_last_name');
  $field_sg_last_name = $field_sg_last_name[0]['value'];
  $name[] = ucwords($field_sg_last_name);
  
  $variables['!client_name'] = implode(' ',$name);
  $variables['!client_fname'] = ucwords($field_sg_first_name);
  
  $here = l('here',url( 'node/' . $node->nid, array('absolute' => TRUE)));
  $msg = "Dear Customer Service Team,
  ".ucwords($field_sg_first_name)." has submitted an Opinion Form. Files are attached. The form can also be accessed by clicking " .$here;
  
  $filepath = array();
  $dentalfilepath = array();
  
  $field_sg_images = field_get_items('node', $node, 'field_sg_images');
  if (sizeof($field_sg_images) > 0) {
		foreach ($field_sg_images as $image) {
      $uri = $image['uri'];
			$imagePath = image_style_url('attachment', $uri);
			$filename = $image['filename'];
      file_get_contents($imagePath);
			$filepath[] = "sites/default/files/styles/attachment/public/{$filename}"; 
		}
	}
  
  if (!empty($filepath)) {
    $filepath[] = variable_get('file_public_path','') .'/surgeons/'  . $node->nid . '.pdf';
  }
  
  $field_dental_images = field_get_items('node', $node, 'field_dental_images');
  if (sizeof($field_dental_images) > 0) {
		foreach ($field_dental_images as $dimage) {
      $uri = $dimage['uri'];
			$dimagePath = image_style_url('attachment', $uri);
			$dfilename = $dimage['filename'];
      file_get_contents($dimagePath);
			$dentalfilepath[] = "sites/default/files/styles/attachment/public/{$dfilename}"; 
		}
	}
  
  if (!empty($dentalfilepath)) {
    $dentalfilepath[] = variable_get('file_public_path','') .'/surgeons/'  . $node->nid . '_dental.pdf';
  }
  
  $from = variable_get('site_mail', '');
  $email = new PHPMailer();
  $email->From      = $from;
  $email->FromName  = 'Stunning Makeovers-Ann Angcao';
  $email->Subject   = $subject;
  $email->Body      = nl2br($msg);
  $email->AddAddress($surgeon_staff);
  $email->addReplyTo = $from;
  $email->isHTML(true);
  
  
  if (sizeof($filepath) > 0) {
    foreach ($filepath as $key => $value) {
      $email->AddAttachment($filepath[$key]);
    }
  }
  
  if (sizeof($dentalfilepath) > 0) {
    foreach ($dentalfilepath as $k => $v) {
      $email->AddAttachment($dentalfilepath[$k]);
    }
  }
    
  if ($email->Send()) {
		drupal_set_message('Your surgeon form was sent successfully');
		watchdog('debug','surgeon mail has been sent.');
	}
	else {
		drupal_set_message('Surgeon Form failed to send. Try again or contact us through the contact form');
		watchdog('debug','surgeon mail has not been sent.');
	}
  
  
  // Social Media Icons in mail footer
  $variables['!social_icons'] = "<div><table border=0 style='margin-top:-30px;' valign='top'>
  <tr><td valign='top'><a href='https://www.facebook.com/stunningmakeovers'><img src='{$base_url}/sites/all/themes/smo/images/mailicon.png'/></a></td>
  <td valign='top'><a href='{$base_url}/index.php?option=com_facileforms&Itemid=57'><img src='{$base_url}/sites/all/themes/smo/images/mailcontact.png'/></a></td>
  <td valign='top'><a href='{$base_url}/'><img src='{$base_url}/sites/all/themes/smo/images/mailhome.png'/></a></td>
  </tr></table></div>";
  
  // Logo in mail
  $variables['!logo'] = "<span style='margin:2px;'><img src='http://stunningmakeovers.com/sites/all/themes/smo/logo.png' width='200px' height='58px'></span>";
  
  // Send mail to client
	
	$messages = NULL;
	$subject = t(variable_get('client_subject', ''), $variables);
	$message = t(variable_get('client_body', ''), $variables);
	$message = nl2br($message);
	$from = variable_get('site_mail', '');
	
  $email2 = new PHPMailer();
  $email2->From      = $from;
  $email2->FromName  = 'Stunning Makeovers-Ann Angcao';
  $email2->Subject   = $subject;
  $email2->Body      = $message;
  $email2->AddAddress($field_sg_email);
  $email2->addReplyTo = $from;
  $email2->isHTML(true);
  
  if (sizeof($filepath) > 0) {
    foreach ($filepath as $key => $value) {
      $email2->AddAttachment($filepath[$key]);
    }
  }
  
  if (sizeof($dentalfilepath) > 0) {
    foreach ($dentalfilepath as $k => $v) {
      $email2->AddAttachment($dentalfilepath[$k]);
    }
  }
  
  $email2->addCC(variable_get('client_cc', ''));
  
	if ($email2->Send()) {
		watchdog('debug','Authorization mail to client has been sent.');
	}
	else {
	  watchdog('debug','Authorization mail has not been sent.');
	}
	
  // Send mail to hospitals
	$message = NULL;
	$subject = t(variable_get('hospital_subject', ''), $variables);
	$message = t(variable_get('hospital_body', ''), $variables);
	$message = nl2br($message);
	$from = variable_get('site_mail', '');
	
  
  $recipient_arr = array();
  if (variable_get('hospital_vejthani', '')) {
    $recipient_arr[] = variable_get('hospital_vejthani', '');
  }
  if (variable_get('hospital_bangpakok', '')) {
    $recipient_arr[] = variable_get('hospital_bangpakok', '');
  }
  if (variable_get('hospital_yanhee', '')) {
    $recipient_arr[] = variable_get('hospital_yanhee', '');
  }
  if (variable_get('hospital_ppsi', '')) {
    $recipient_arr[] = variable_get('hospital_ppsi', '');
  }
  if (variable_get('hospital_sikarin', '')) {
    $recipient_arr[] = variable_get('hospital_sikarin', '');
  }
  
  if (sizeof($recipient_arr) > 0) {
		foreach ($recipient_arr as $recipients) {
			$rec = explode(',', $recipients);
      
      $email3 = new PHPMailer();
      $email3->From      = $from;
      $email3->FromName  = 'Stunning Makeovers-Ann Angcao';
      $email3->Subject   = $subject;
      $email3->Body      = $message;
      $email3->addReplyTo = $from;
      $email3->AddAddress($rec[0]);
      $email3->isHTML(true);
      array_shift($rec);
      
      if (sizeof($rec) >= 1) {
        foreach ($rec as $rec_emails) {
          $email3->addCC($rec_emails);
        }
      }
    
      $email3->addCC(variable_get('hospital_cc', ''));
      
       if (sizeof($filepath) > 0) {
         foreach ($filepath as $key => $value) {
           $email3->AddAttachment($filepath[$key]);
         }
       }
  
			if ($email3->Send()) {
			  watchdog('debug','Enquiry mail to hospitals have been sent.');
			}
			else {
				watchdog('debug','Enquiry mail to hospitals has not been sent.');
			}
	  } // end foreach
	} // end if
  
  // Send mail to dental hospitals
	$message = NULL;
	$subject = t(variable_get('dental_hospital_subject', ''), $variables);
	$message = t(variable_get('dental_hospital_body', ''), $variables);
	$message = nl2br($message);
	$from = variable_get('site_mail', '');
  
  $dental_recipient_arr = array();
  if (variable_get('hospital_smile', '')) {
    $dental_recipient_arr[] = variable_get('hospital_smile', '');
  }
  
  if ( sizeof($dental_recipient_arr) > 0 && sizeof($dentalfilepath) > 0) {
		foreach ($dental_recipient_arr as $recipients) {
			$rec = explode(',', $recipients);
      
      $email3 = new PHPMailer();
      $email3->From      = $from;
      $email3->FromName  = 'Stunning Makeovers-Ann Angcao';
      $email3->Subject   = $subject;
      $email3->Body      = $message;
      $email3->addReplyTo = $from;
      $email3->AddAddress($rec[0]);
      $email3->isHTML(true);
      
      if (sizeof($rec) >= 1) {
        foreach ($rec as $rec_emails) {
          $email3->addCC($rec_emails);
        }
      }
    
      $email3->addCC(variable_get('hospital_cc', ''));
      
       if (sizeof($dentalfilepath) > 0) {
         foreach ($dentalfilepath as $k => $v) {
           $email3->AddAttachment($dentalfilepath[$k]);
         }
       }
       
      if ($email3->Send()) {
			  watchdog('debug','Enquiry mail to dental hospitals have been sent.');
			}
			else {
				watchdog('debug','Enquiry mail to dental hospitals has not been sent.');
			}
	  } // end foreach
	} // end if
}


/**
 * Attach pdf & send mail
 */
function _stu_forms_send_dental($nid) {
  global $base_url, $user;
  require_once(libraries_get_path('phpmailer') . '/class.phpmailer.php');
  $language = language_default();
  
  $node = node_load($nid, NULL, TRUE);
  
  $subject = 'Opinion Form by '. $node->title;
  $msg = 'See Attached.';
  $surgeon_staff = variable_get('surgeon_staff', '');
  $from = variable_get('site_mail', '');
  
  $field_sg_email = field_get_items('node', $node, 'field_sg_email');
  $field_sg_email = $field_sg_email[0]['email'];
  
  $field_sg_first_name = field_get_items('node', $node, 'field_sg_first_name');
  $field_sg_first_name = $field_sg_first_name[0]['value'];
  $name[] = ucwords($field_sg_first_name);
  
  $field_sg_last_name = field_get_items('node', $node, 'field_sg_last_name');
  $field_sg_last_name = $field_sg_last_name[0]['value'];
  $name[] = ucwords($field_sg_last_name);
  
  $variables['!client_name'] = implode(' ',$name);
  $variables['!client_fname'] = ucwords($field_sg_first_name);
  
  $here = l('here',url( 'node/' . $node->nid, array('absolute' => TRUE)));
  $msg = "Dear Customer Service Team,
  ".ucwords($field_sg_first_name)." has submitted an Opinion Form. Files are attached. The form can also be accessed by clicking " .$here;
  
  $filepath = array();
  $filepath[] = variable_get('file_public_path','') .'/surgeons/'  . $node->nid . '_dental.pdf';
  
  $field_sg_images = field_get_items('node', $node, 'field_sg_images');
  if (sizeof($field_sg_images) > 0) {
		foreach ($field_sg_images as $image) {
      $uri = $image['uri'];
			$imagePath = image_style_url('attachment', $uri);
			$filename = $image['filename'];
      file_get_contents($imagePath);
			$filepath[] = "sites/default/files/styles/attachment/public/{$filename}"; 
		}
	}
  
  $from = variable_get('site_mail', '');
  $email = new PHPMailer();
  $email->From      = $from;
  $email->FromName  = 'Stunning Makeovers-Ann Angcao';
  $email->Subject   = $subject;
  $email->Body      = nl2br($msg);
  $email->AddAddress($surgeon_staff);
  $email->addReplyTo = $from;
  $email->isHTML(true);
  
  
  if (sizeof($filepath) > 0) {
    foreach ($filepath as $key => $value) {
      $email->AddAttachment($filepath[$key]);
    }
  }
    
  if ($email->Send()) {
		drupal_set_message('Your surgeon form was sent successfully');
		watchdog('debug','Dental surgeon mail has been sent.');
	}
	else {
		drupal_set_message('Dental Surgeon Form failed to send. Try again or contact us through the contact form');
		watchdog('debug','Dental surgeon mail has not been sent.');
	}
  
  
  // Social Media Icons in mail footer
  $variables['!social_icons'] = "<div><table border=0 style='margin-top:-30px;' valign='top'>
  <tr><td valign='top'><a href='https://www.facebook.com/stunningmakeovers'><img src='{$base_url}/sites/all/themes/smo/images/mailicon.png'/></a></td>
  <td valign='top'><a href='{$base_url}/index.php?option=com_facileforms&Itemid=57'><img src='{$base_url}/sites/all/themes/smo/images/mailcontact.png'/></a></td>
  <td valign='top'><a href='{$base_url}/'><img src='{$base_url}/sites/all/themes/smo/images/mailhome.png'/></a></td>
  </tr></table></div>";
  
  // Logo in mail
  $variables['!logo'] = "<span style='margin:2px;'><img src='http://stunningmakeovers.com/sites/all/themes/smo/logo.png' width='200px' height='58px'></span>";
  
  // Send mail to client
	$messages = NULL;
	$subject = t(variable_get('client_subject', ''), $variables);
	$message = t(variable_get('client_body', ''), $variables);
	$message = nl2br($message);
	$from = variable_get('site_mail', '');
	
  $email2 = new PHPMailer();
  $email2->From      = $from;
  $email2->FromName  = 'Stunning Makeovers-Ann Angcao';
  $email2->Subject   = $subject;
  $email2->Body      = $message;
  $email2->AddAddress($field_sg_email);
  $email2->addReplyTo = $from;
  $email2->isHTML(true);
  
  if (sizeof($filepath) > 0) {
    foreach ($filepath as $key => $value) {
      $email2->AddAttachment($filepath[$key]);
    }
  }
  
  $email2->addCC(variable_get('dental_client_cc', ''));
  
	if ($email2->Send()) {
		watchdog('debug','Authorization mail to client has been sent.');
	}
	else {
	  watchdog('debug','Authorization mail has not been sent.');
	}
	
	
	// Send mail to hospitals
	$message = NULL;
	$subject = t(variable_get('dental_hospital_subject', ''), $variables);
	$message = t(variable_get('dental_hospital_body', ''), $variables);
	$message = nl2br($message);
	$from = variable_get('site_mail', '');
	
  
  $recipient_arr = array();
  $recipient_arr[] = variable_get('hospital_smile', '');
  if (sizeof($recipient_arr) > 0) {
		foreach ($recipient_arr as $recipients) {
			$rec = explode(',', $recipients);
      
      $email3 = new PHPMailer();
      $email3->From      = $from;
      $email3->FromName  = 'Stunning Makeovers-Ann Angcao';
      $email3->Subject   = $subject;
      $email3->Body      = $message;
      $email3->addReplyTo = $from;
      $email3->AddAddress($rec[0]);
      $email3->isHTML(true);
      array_shift($rec);
      
      if (sizeof($rec) >= 1) {
        foreach ($rec as $rec_emails) {
          $email3->addCC($rec_emails);
        }
      }
    
      $email3->addCC(variable_get('hospital_cc', ''));
      
       if (sizeof($filepath) > 0) {
         foreach ($filepath as $key => $value) {
           $email3->AddAttachment($filepath[$key]);
         }
       }
  
			if ($email3->Send()) {
			  watchdog('debug','Enquiry mail for dental to hospitals have been sent.');
			}
			else {
				watchdog('debug','Enquiry mail for dental to hospitals has not been sent.');
			}
	  } // end foreach
	} // end if
}


/**
 * Generate PDF
 */
function _customGeneratePdf($node) {
  module_load_include('inc', 'print', 'includes/print');
	require 'sites/all/modules/print/dompdf/dompdf_config.inc.php';
	define("DOMPDF_ENABLE_PHP", TRUE);
  define("DOMPDF_ENABLE_REMOTE", TRUE);
  define('DOMPDF_TEMP_DIR', file_directory_temp());
  define('DOMPDF_ENABLE_REMOTE', 1);
  
	$logo_url = theme_get_setting('logo');
  $print_logo = theme('image', array('path' => $logo_url, 'alt' => variable_get('site_name', 'Drupal'), 'attributes' => array('class' => 'print-logo', 'id' => 'logo')));
  $html = theme('surgeon_pdf',array('node' => $node, 'print_logo' => $print_logo));
  
  $dompdf = new DOMPDF();
  $data = '<html>';
  $data .= $html;
  $data .= '</html>';
  $dompdf->load_html($data);
  $dompdf->render();
  
  $path = 'public://surgeons';
  file_prepare_directory($path, FILE_CREATE_DIRECTORY);
  $filename = $node->nid ;
  $pdfoutput = $dompdf->output();
  $pdf_path = $path . '/' . $filename . '.pdf';
  $fp = fopen($pdf_path, "a");
  fwrite($fp, $pdfoutput);
  fclose($fp);  
  return $pdf_path;
}

/**
 * Generate PDF For Dental
 */
function _customDentalPdf($node) {
	module_load_include('inc', 'print', 'includes/print');
	require 'sites/all/modules/print/dompdf/dompdf_config.inc.php';
	define("DOMPDF_ENABLE_PHP", TRUE);
  define("DOMPDF_ENABLE_REMOTE", TRUE);
  define('DOMPDF_TEMP_DIR', file_directory_temp());
  define('DOMPDF_ENABLE_REMOTE', 1);
  
	$logo_url = theme_get_setting('logo');
  $print_logo = theme('image', array('path' => $logo_url, 'alt' => variable_get('site_name', 'Drupal'), 'attributes' => array('class' => 'print-logo', 'id' => 'logo')));
  $html = theme('dental_pdf',array('node' => $node, 'print_logo' => $print_logo));
  
  $dompdf = new DOMPDF();
  $data = '<html>';
  $data .= $html;
  $data .= '</html>';
  $dompdf->load_html($data);
  $dompdf->render();
  
  $path = 'public://surgeons';
  file_prepare_directory($path, FILE_CREATE_DIRECTORY);
  $filename = $node->nid ;
  $pdfoutput = $dompdf->output();
  $pdf_path = $path . '/' . $filename . '_dental.pdf';
  $fp = fopen($pdf_path, "a");
  fwrite($fp, $pdfoutput);
  fclose($fp);  
  return $pdf_path;
}

/**
 * Hook_element_info_alter()
 */
function stu_forms_element_info_alter(&$type) {
  $type['radios']['#process'][] = '_stu_forms_remove_radio_na';
}

/**
 * Callback
 */
function _stu_forms_remove_radio_na($element) {
  unset($element['#options']['_none']);
  unset($element['_none']);
  return $element;
}

/**
 * Hook_block_view_alter()
 */
function stu_forms_block_view_alter(&$data, $block) {
  switch ($block->delta) {
    case 'home_destinations-block_2':
      $data['subject'] = l(t('Destinations'),'node/96', array('attributes' => array('class' => 'block-left'))) .' ' . l(t('view all'),'node/96', array('attributes' => array('class' => 'block-right')));
    break;
    
    case 'home_packages-block_2':
      $data['subject'] = l(t('Special Packages'),'node/73', array('attributes' => array('class' => 'block-left'))) .' ' .
      l(t('view all'),'node/73', array('attributes' => array('class' => 'block-right')));
    break;
    
    case 'home_testimonials-block_2':
      $data['subject'] = l(t('What Clients Say'),'node/28', array('attributes' => array('class' => 'block-left'))) .' ' .
      l(t('view all'),'node/28', array('attributes' => array('class' => 'block-right')));
    break;
  }
}

/**
 * Hook_views_pre_render()
 */
function stu_forms_views_pre_render(&$view) {
	
	if (isset($_SESSION['CRATE'])) {
	  $rate = $_SESSION['CRATE'];
	}
	else {
		$rate = 1;
	}
	
	if(isset($_SESSION['CURR'])) {
	  $curr = $_SESSION['CURR'];
	}
	else {
		$curr = 'THB';
	}
	
	if ($view->name == "procedure_price") {
		$results = &$view->result;  
		foreach ($results as $key => $result) {
			if (is_numeric($results[$key]->field_field_procedure_cost[0]['raw']['value'])) {
			$results[$key]->field_field_procedure_cost[0]['rendered']['#markup'] = 
				theme('format_currency', array('price' => $results[$key]->field_field_procedure_cost[0]['raw']['value'] / $rate, 'param' => $curr));
			}
			if (is_numeric($results[$key]->field_field_procedure_cost_1[0]['raw']['value'])) {
			$results[$key]->field_field_procedure_cost_1[0]['rendered']['#markup'] = 
				theme('format_currency', array('price' => $results[$key]->field_field_procedure_cost_1[0]['raw']['value'] / $rate,'param' => $curr));
			}
		}
	}
}


function _custom_pre_next($type) {
	/*$query = db_select('node','n');
	$query->join('content_type_doctor','doctor','n.nid = doctor.nid');
	$query->fields('n',array('nid'));
	$query->condition('doctor.field_doctor_type_value', $type, '=');
	/*$query->orderBy('doctor.field_doctor_type_value', 'DESC');
  $query->orderBy('doctor.field_doctor_facility_nid', 'ASC');*/
  //$query->orderBy('n.title', 'ASC');
  //$results = $query->execute()->fetchAll();
  $array = array($type);
	$view = views_get_view('custom_pre_next');
	$view->set_display("page");
	$view->set_arguments($array);
	$view->pre_execute();
	$view->execute();
	$content = $view->render();
  $results = $view->result;
  return $results; 
}

/**
 * Get nid by tid
 */
function get_nid_by_tid($tid) {
  $query = db_select('node','n');
	$query->join('taxonomy_index','taxonomy_index','n.nid = taxonomy_index.nid');
	$query->fields('n',array('nid'));
	$query->condition('n.type', 'procedure', '=');
	$query->condition('taxonomy_index.tid', $tid, '=');
	$query->orderBy('n.title', 'ASC');
  $nid = $query->execute()->fetchField();
  return $nid; 
}

/**
 * Get All parent tids
 */
function _getAllParents() {
	$parent_term = array();
  $query = db_select('taxonomy_term_hierarchy','p');
	$query->fields('p',array('tid'));
	$query->condition('p.parent', 0, '=');
	$parents = $query->execute()->fetchAll();
	if (sizeof($parents)) {
	  foreach ($parents as $result) {
		  $parent_term[] = 	$result->tid;
		}	 
	}
	return $parent_term;
}

/**
 * First Name: 
 * Last Name: 
 * Gender: 
 * Email Address: 
 * Mobile Phone Number: 
 * Daytime Phone Number: 
 * City:
 * Country:
 * Surgery:
 * Expectations
 * Intends to travel:
 * Preferred Destination: 
 * Preferred Contact: 
 * 
 * {
    "apiUrl": "https://api.insight.ly",
    "apiKey": "c0407969-6217-4572-855c-0aa32e8a7bd5",
    "salutation": "Ms",
    "firstName": "Jessica",
    "lastName": "Denver",
    "background": "Rejoined to the company",
    "imageUrl": "http://www.livescanfp.com/images/image_6.jpg",
    "defaultLinkedOrganisation": "55390034",
    "ownerUserId": "106933074",
    "visibleTo": "Everyone",
    "visibleTeamId": "2670029",
    "visibleUserIds": "",
    "addresses": [      {
         "ADDRESS_TYPE": "Home",
         "STREET": "Jungle Street",
         "CITY": "Horana",
         "STATE": "Eastern Province",
         "POSTCODE": "09567",
         "COUNTRY": "Sri Lanka"
      }],
    "dates": [      {
         "OCCASION_NAME": "Induction",
         "OCCASION_DATE": "2015-04-28 00:00:00",
         "REPEAT_YEARLY": false,
         "CREATE_TASK_YEARLY": false
      }],
    "tags": [
         {"TAG_NAME": "C++"},
         {"TAG_NAME": "SE"}
      ],
    "links": [],
    "customFields": [      {
         "CUSTOM_FIELD_ID": "CONTACT_FIELD_1",
         "FIELD_VALUE": "895772964V"
      }],
    "emailLinks": [
                  {
            "EMAIL_ID": 23031616,
            "CONTACT_ID": 105239940,
            "ORGANISATION_ID": 55390034,
            "OPPORTUNITY_ID": 6322715,
            "PROJECT_ID": 2119188
         }
      ],
    "contactLinks": [],
    "contactInfos": [      {
         "TYPE": "EMAIL",
         "SUBTYPE": "",
         "LABEL": "Work",
         "DETAIL": "jessica.d@gmail.com"
      }]
}
Related Insightly documentation
https://api.insight.ly/v2.1/Help/A
* https://docs.wso2.com/display/ESBCONNECTORS/Working+with+Contacts+in+Insightly
 */
function _sendDataToCRM($node) {
  $field_sg_email = field_get_items('node', $node, 'field_sg_email');
  $field_sg_email = $field_sg_email[0]['email'];
  
  $field_sg_first_name = field_get_items('node', $node, 'field_sg_first_name');
  $field_sg_first_name = $field_sg_first_name[0]['value'];

  $field_sg_last_name = field_get_items('node', $node, 'field_sg_last_name');
  $field_sg_last_name = $field_sg_last_name[0]['value'];
  
  $field_sg_gender = field_get_items('node', $node, 'field_sg_gender');
  $field_sg_gender = $field_sg_gender[0]['value'];
  
  $field_sg_phone = field_get_items('node', $node, 'field_sg_phone');
  $field_sg_phone = $field_sg_phone[0]['value'];
  
  $field_sg_postal_street_address = field_get_items('node', $node, 'field_sg_postal_street_address');
  $field_sg_postal_street_address = $field_sg_postal_street_address[0]['value'];
  
  
  $field_sg_postcode_zip = field_get_items('node', $node, 'field_sg_postcode_zip');
  $field_sg_postcode_zip = $field_sg_postcode_zip[0]['value'];
  
  $field_sg_region_state = field_get_items('node', $node, 'field_sg_region_state');
  $field_sg_region_state = $field_sg_region_state[0]['value'];
  
  $field_sg_city = field_get_items('node', $node, 'field_sg_city');
  $field_sg_city = $field_sg_city[0]['value'];
  
  $field_sg_countries = field_get_items('node', $node, 'field_sg_countries');
  $field_sg_countries = $field_sg_countries[0]['value'];
  
  $terms = array();
  $field_surgical_procedures = field_get_items('node', $node, 'field_surgical_procedures');
  if(sizeof($field_surgical_procedures) > 0) {
    foreach ($field_surgical_procedures as $key => $value) {
       $terms[] = db_select('taxonomy_term_data', 'term')->fields('term',array('name'))->condition('tid', $value[tid], '=')->execute()->fetchField(); 
    }
  }
  
  $field_hairtransplant_procedures = field_get_items('node', $node, 'field_hairtransplant_procedures');
  if(sizeof($field_hairtransplant_procedures) > 0) {
    foreach ($field_hairtransplant_procedures as $key => $value) {
       $terms[] = db_select('taxonomy_term_data', 'term')->fields('term',array('name'))->condition('tid', $value[tid], '=')->execute()->fetchField(); 
    }
  }
  
  $field_dental_procedures = field_get_items('node', $node, 'field_dental_procedures');
  if(sizeof($field_dental_procedures) > 0) {
    foreach ($field_dental_procedures as $key => $value) {
       $terms[] = db_select('taxonomy_term_data', 'term')->fields('term',array('name'))->condition('tid', $value[tid], '=')->execute()->fetchField(); 
    }
  }
  
  if (sizeof($terms) > 0) {
    $surgical_procedures = implode(', ',$terms);  
  }
  
  $field_expect_from_surgery = field_get_items('node', $node, 'field_expect_from_surgery');
  $field_expect_from_surgery = $field_expect_from_surgery[0]['value'];
  
  $field_travel_preferences = field_get_items('node', $node, 'field_travel_preferences');
  $field_travel_preferences = $field_travel_preferences[0]['value'];
  
  $field_surgery_location	 = field_get_items('node', $node, 'field_surgery_location');
  $field_surgery_location	 = $field_surgery_location[0]['nid'];
  $surgery_location = NULL;
  if (isset($field_surgery_location)) {
    if ($field_surgery_location == 2) {
      $surgery_location = "Bangkok"; 
    }
    else if ($field_surgery_location == 21) {
      $surgery_location = "Phuket";
    }  
  }
  
  $field_sg_prefer_contact = field_get_items('node', $node, 'field_sg_prefer_contact');
  $field_sg_prefer_contact = $field_sg_prefer_contact[0]['value'];
  
  $lang = $node->language;

  if ($field_sg_last_name) {
    $last_name = $field_sg_last_name;
  }
  else {
    $last_name = '';
  }

  if ($field_sg_first_name) {
    $first_name = $field_sg_first_name;
  }
  else {
    $first_name = '';
  }

  if ($field_sg_phone) {
    $phone_contact = '{"CONTACT_INFO_ID":0,"TYPE":"PHONE","SUBTYPE":"Work","LABEL":null,"DETAIL":"' . $field_sg_phone . '"}, ';
  }
  else {
    $phone_contact = '';
  }

  if ($field_sg_email) {
    $email_contact = '{"CONTACT_INFO_ID":1,"TYPE":"EMAIL","SUBTYPE":"Work","LABEL":null,"DETAIL":"' . $field_sg_email . '"}';
  }
  else {
    $email_contact = '';
  }
  
  if ($field_sg_gender) {
    $gender = '{"CUSTOM_FIELD_ID":"Gender__c", "FIELD_VALUE":"' . $field_sg_gender . '"}, ';
  }
  else {
    $gender = '';
  }
  
  if ($surgical_procedures) {
    $surgery = '{"CUSTOM_FIELD_ID":"Surgery__c", "FIELD_VALUE":"' . $surgical_procedures . '"}, ';
  }
  else {
    $surgery = '';
  }
   
  if ($field_expect_from_surgery) {
    $expect_from_surgery = '{"CUSTOM_FIELD_ID":"Expectations__c", "FIELD_VALUE":"' . $field_expect_from_surgery . '"}, ';
  }
  else {
    $expect_from_surgery = '';
  }
  
  if ($field_travel_preferences) {
    $travel_preferences = '{"CUSTOM_FIELD_ID":"Intends_to_travel__c", "FIELD_VALUE":"' . $field_travel_preferences . '"}, ';
  }
  else {
    $travel_preferences = '';
  }
  
  if ($surgery_location) {
    $preferred_destination = '{"CUSTOM_FIELD_ID":"Preferred_Destination___c", "FIELD_VALUE":"' . $surgery_location . '"}, ';
  }
  else {
    $preferred_destination = '';
  }
  
  if ($field_sg_prefer_contact) {
    $prefer_contact = '{"CUSTOM_FIELD_ID":"Preferred_Contact__c", "FIELD_VALUE":"' . $field_sg_prefer_contact . '"}';
  }
  else {
    $prefer_contact = '';
  }
  
  
  $all_fields_on_my_website = field_info_fields();
  $allowed_values = list_allowed_values($all_fields_on_my_website["field_sg_countries"]);
  
  $address = '{
         "ADDRESS_TYPE": "Postal",
         "STREET": "'.$field_sg_postal_street_address.'",
         "CITY": "'.$field_sg_city.'",
         "STATE": "'.$field_sg_region_state.'",
         "POSTCODE": "'.$field_sg_postcode_zip.'",
         "COUNTRY": "'.$allowed_values[$field_sg_countries].'"
      }';
  
  date_default_timezone_set('UTC');
  $date = date('Y-m-d H:m:s');
  
  $customFields = $gender . ' ' . $surgery . ' ' . $expect_from_surgery . ' ' . $travel_preferences . ' ' .  $preferred_destination . ' ' . $prefer_contact;

  $contact = '{"CONTACT_ID":0,"SALUTATION":null,"FIRST_NAME":"' . $first_name . '","LAST_NAME":"' . $last_name . '","BACKGROUND":null,"IMAGE_URL":"http://s3.amazonaws.com/insightly.userfiles/367601/","DEFAULT_LINKED_ORGANISATION":null,"DATE_CREATED_UTC":"' . $date . '","DATE_UPDATED_UTC":"' . $date . '","VISIBLE_TO":"EVERYONE","VISIBLE_TEAM_ID":null,"VISIBLE_USER_IDS":null,"CUSTOMFIELDS":[' . $customFields . '],"ADDRESSES":['.$address.'],"CONTACTINFOS":[' . $phone_contact . ' ' . $email_contact . '],"DATES":[],"TAGS":[],"LINKS":[],"CONTACTLINKS":[],"EMAILLINKS":null}';

  $url = 'https://api.insight.ly/v2.1/Contacts';

  $user = variable_get('my_insightly_integration_for_drupal_apikey', 0);
  if ($user == 0) {
    watchdog('my_insightly_integration_for_drupal_apikey', 'API key not set!');
  }
  else {
    $user = base64_encode($user);
    $http_options = array(
      'method' => 'POST',
      'headers' => array(
        'Content-Type' => 'application/json',
        'Authorization' => 'Basic ' . $user,
      ),
      'data' => $contact,
    );
    drupal_http_request($url, $http_options);
  }
}

/**
 * Settings form.
 */
function _my_insightly_integration_for_drupal_form($form, &$form_state) {
  $form['my_insightly_integration_for_drupal_apikey'] = array(
    '#type' => 'textfield',
    '#title' => t('Your Insight.ly API key'),
    '#default_value' => variable_get('my_insightly_integration_for_drupal_apikey', 0),
    '#size' => 60,
    '#maxlength' => 60,
    '#description' => t('Your Insight.ly API key used in authentication.'),
    '#required' => TRUE,
  );
  return system_settings_form($form);
}


/**
 * Impelements hook_menu_alter()
 */
function stu_forms_menu_alter(&$items) {
  $items['user/%user']['access arguments'] = array('access user profiles');
  $items['user/%user']['access callback'] = 'user_access';
  $items['user/%user/edit']['access arguments'] = array('administer users');
  $items['user/%user/edit']['access callback'] = 'user_access';
}

/**
 * Impelements hook_user_login()
 */
function stu_forms_user_login(&$edit, $account) {
  if(isset($account->uid) && !empty($account->uid) && in_array('other_user', array_values($account->roles))) {
    $nid = db_select('node','node')
      ->fields('node',array('nid'))
      ->condition('node.uid',$account->uid)
      ->condition('node.type','surgeon')->execute()->fetchField();
    if ($nid) {
      $_GET['destination'] = "node/{$nid}/edit";     
    }  
  }
}

/**
 * Implements hook_cron().
 *
 * Blocked the other_user user.
 */
function stu_forms_cron() {
  $next_24 = variable_get('next_24', 0);
  if ($next_24 < time()) {
    $query = db_select('users','u');
    $query->join('users_roles','r','u.uid = r.uid');
    $query->fields('u', array('uid'));
    $query->condition('r.rid', 3);
    $query->condition('u.status', 1);
    $results = $query->execute()->fetchAll();
    if (sizeof($results) > 0) {
      foreach ($results as $result) {
        $userload = user_load($result->uid);
        $userload->status = 0;
        user_save($userload);  
      }  
    }
    variable_set('next_24', strtotime('+1 day'));  
  }
}

