<?php
module_load_include('inc', 'stu_schedule', 'includes/stu_schedule.pages');

/**
 * Implementing hook_init()
 */
function stu_schedule_init() {
	$arg = arg();
	if ($arg[0] == 'node' && is_numeric($arg[1])) {
		$node = menu_get_object();
		if($node->type == 'makeovers_master') {
		  drupal_add_js(drupal_get_path('module','stu_schedule') . '/js/stu_schedule.js');
		}
	}
	if ($arg[0] == 'node' && $arg[1] == 'add' && $arg[2] == 'makeovers-master') {
		drupal_add_js(drupal_get_path('module','stu_schedule') . '/js/stu_schedule.js');
	}
}

/**
 * Implementing hook_menu()
 */
function stu_schedule_menu() {
	$items['admin/makeover/schedule'] = array(
		'title'=>'Makeover Schedules Settings',
		'page callback'=>'drupal_get_form',
		'page arguments' => array('makeover_schedule_settings'),
	  'access arguments' => array('makeover admin access'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'includes/stu_schedule.pages.inc',
		'weight' => 5,
	);
	$items['admin/makeover/schedule/hotel'] = array(
		'title'=>'Hotels Settings',
		'page callback'=>'drupal_get_form',
		'page arguments' => array('schedule_hotel_settings'),
	  'access arguments' => array('makeover admin access'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'includes/stu_schedule.admin.inc',
		'weight' => 5,
	);
	$items['admin/makeover/schedule/hospital'] = array(
		'title'=>'Hospitals Settings',
		'page callback'=>'drupal_get_form',
		'page arguments' => array('schedule_hospitals_settings'),
	  'access arguments' => array('makeover admin access'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'includes/stu_schedule.admin.inc',
		'weight' => 5,
	);
	$items['admin/makeover/schedule/dental'] = array(
		'title'=>'Dental Hospitals Settings',
		'page callback'=>'drupal_get_form',
		'page arguments' => array('schedule_dental_hospitals_settings'),
	  'access arguments' => array('makeover admin access'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'includes/stu_schedule.admin.inc',
		'weight' => 5,
	);
  return $items;
}

/**
 * Implementing hook_theme()
 */
function stu_schedule_theme($existing, $type, $theme, $path) {
  $path = drupal_get_path('module', 'stu_schedule') .'/templates';
	return array(
	  'hotel_reservation' => array(
		  'variables' => array(
		    'guestname' => NULL, 
		    'guestname2' => NULL,
			  'guestname3' => NULL,
			  'guestname4' => NULL, 
		    'bedding' => NULL, 
		    'checkin' => NULL,
		    'checkout' => NULL,
		    'roomtype' => NULL,
		    'ratepernight' => NULL,
		    'numberofnights' => NULL,
		    'totalpayable' => NULL,
		    'hoteltoairport' => NULL,
		    'hotelname' => NULL,
		    'rollaway_bed' => NULL,
		    'qualify_for_upgrade' => NULL,
			'upgrade_room_type' => NULL,
		   ),
		  'template' => 'hotel--reservation',
		  'path' => $path,
		),
	  'transfers_stunning_makeovers' => array(
		  'variables' => array(
		    'guestname' => NULL,
		    'guestname2' => NULL,
				'guestname3' => NULL,
				'guestname4' => NULL,
		    'arrival' => NULL,
			  'departure' => NULL,
		   ),
		  'template' => 'transfers--stunning--makeovers',
		  'path' => $path,
		),
		'tours_stunning_makeovers' => array (
		  'variables' => array(
		    'guestname' => NULL,
		    'guestname2' => NULL,
				'guestname3' => NULL,
				'guestname4' => NULL,
		    'iterations' => NULL,
		   ),
		  'template' => 'tours--stunning--makeovers',
		  'path' => $path,
		),
		'cruise_stunning_makeovers' => array (
		  'variables' => array(
		    'guestname' => NULL,
		    'guestname2' => NULL,
				'guestname3' => NULL,
				'guestname4' => NULL,
		    'iterations' => NULL,
		   ),
		  'template' => 'cruise--stunning--makeovers',
		  'path' => $path,
		),
		'stunning_makeovers_schedule_daycare' => array(
		  'variables' => array(
		    'values' => NULL,
		    'node' => NULL,
		    'print_logo' => NULL,
		   ),
		  'template' => 'stunning--makeovers--schedule--daycare',
		  'path' => $path . '/daycare',
		),
		'stunning_makeovers_schedule_not_daycare' => array(
		  'variables' => array(
		    'values' => NULL,
		    'node' => NULL,
		    'print_logo' => NULL,
		   ),
		  'template' => 'stunning--makeovers--schedule--not--daycare',
		  'path' => $path . '/notdaycare',
		),
	); 
}

/**
 * Implements hook_entity_update().
 */
function stu_schedule_entity_presave($entity, $type) {
  if ($type == 'node' && $entity->type == 'makeovers_master') {
    $language = $entity->language;
    
    // Departure date
    foreach ($entity->field_departure_flight_details[$language] as $departure_flight) {
			// Load field collection item.
      $field_collection = field_collection_field_get_entity($departure_flight);
       if (!empty($field_collection->field_departure_date[$language][0]['value'])) {
				 $date = $field_collection->field_departure_date[$language][0];
         if (empty($field_collection->field_transfers_pickup_date[$language][0]['value'])) {
				   $field_collection->field_transfers_pickup_date[$language][0]['value'] = date('Y-m-d H:i:s', strtotime("-4 hours", strtotime($date['value'])));
			   }
       }
		 }
		
		// Arrival date
    /*foreach ($entity->field_arrival_flight_details[$language] as $arrival_flight) {
			// Load field collection item.
      $field_collection = field_collection_field_get_entity($arrival_flight);
       if (!empty($field_collection->field_flight_date[$language][0]['value'])) {
				 $date = $field_collection->field_flight_date[$language][0];
				 $field_collection->field_transfers_pickup_date[$language][0]['value'] = date('Y-m-d H:i:s', strtotime("+15 minutes", strtotime($date['value'])));
			 }
		 }*/
    
    foreach ($entity->field_tour[$language] as $field_tour) {
      // Load field collection item.
      $field_collection = field_collection_field_get_entity($field_tour);
      
      if (!empty($field_collection->field_tour_name[$language][0]['value'])) {
			  if ($field_collection->field_tour_name[$language][0]['value'] == 'Chaophraya River Dinner Cruise') {
					$hrs = 4;
					$field_collection->field_tour_duration_estimated[$language][0]['value'] = '4 hours';
				}
				else if ($field_collection->field_tour_name[$language][0]['value'] == 'Grand Palace Tour') {
					$hrs = 5;
					$field_collection->field_tour_duration_estimated[$language][0]['value'] = 'Half Day';
				}
				else if ($field_collection->field_tour_name[$language][0]['value'] == 'Temple City Tour') {
					$hrs = 5;
					$field_collection->field_tour_duration_estimated[$language][0]['value'] = 'Half Day';
				}
				else if ($field_collection->field_tour_name[$language][0]['value'] == 'Floating Market') {
					$hrs = 5;
					$field_collection->field_tour_duration_estimated[$language][0]['value'] = 'Half Day';
				}
				else if ($field_collection->field_tour_name[$language][0]['value'] == 'Floating Market + Crocodile Farm + Lunch') {
					$hrs = 10;
					$field_collection->field_tour_duration_estimated[$language][0]['value'] = 'Full Day';
				}
				else if ($field_collection->field_tour_name[$language][0]['value'] == 'Floating Market + Rose Garden + Lunch') {
					$hrs = 10;
					$field_collection->field_tour_duration_estimated[$language][0]['value'] = 'Full Day';
				}
				else if ($field_collection->field_tour_name[$language][0]['value'] == 'Floating Market + Crocodile + Rose Garden + Lunch') {
					$hrs = 10;
					$field_collection->field_tour_duration_estimated[$language][0]['value'] = 'Full Day';
				}
				else if ($field_collection->field_tour_name[$language][0]['value'] == 'Floating Market + Kanchanaburi/River Kwai + Lunch') {
					$hrs = 10;
					$field_collection->field_tour_duration_estimated[$language][0]['value'] = 'Full Day';
				}
			}
      
      if (!empty($field_collection->field_tour_date_time[$language][0]['value'])){
				/*
				 * 
				 * $field_collection->field_arrive_back_at_hotel[$language][0] = array(
					'value' => format_date($date, 'custom', 'h:ia', date_default_timezone()),
					'timezone' => date_default_timezone(), 
					'timezone_db' => 'UTC',
				);*/
				
				$date = $field_collection->field_tour_date_time[LANGUAGE_NONE][0];
				$date_object = new DateObject($date['value'], new DateTimeZone('UTC'));
				$date_object->setTimezone(new DateTimeZone(date_default_timezone()));
				$finaldate = date_format_date($date_object, 'custom', 'Y-m-d h:ia'); 
			  $field_collection->field_arrive_back_at_hotel[$language][0]['value'] = date("h:ia", strtotime("+{$hrs} hours", strtotime($finaldate)));
		  }
      $field_collection->save(TRUE);
    }
  }
}

function stu_schedule_mail_alter(&$message) {
  
}

/**
 * hook_form_field_ui_field_edit_form_alter()
 */
function stu_schedule_form_field_ui_field_edit_form_alter(&$form, &$form_state, $form_id) {
	if ($form['#field']['type'] == 'field_collection') {
    $form['field']['cardinality']['#options'] = drupal_map_assoc(range(1, 20));
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Adds two fields to the node form, second only appears after first is enabled.
 */
function stu_schedule_form_node_form_alter(&$form, &$form_state, $form_id) {
	$arg = arg();
	if ($form_id == 'makeovers_master_node_form') {
	unset($form['field_clients_passport_name']);
		if ($arg[0] == 'node' && $arg[1] == 'add') {
			// Hide some field
			$form['field_cs_txt'][LANGUAGE_NONE][0]['field_cstxt_action'][LANGUAGE_NONE][0]['value']['#value'] = 'Pre-Departure Call';
		  $form['field_cs_txt'][LANGUAGE_NONE][1]['field_cstxt_action'][LANGUAGE_NONE][0]['value']['#value'] = 'Flys out';
		  $form['field_cs_txt'][LANGUAGE_NONE][2]['field_cstxt_action'][LANGUAGE_NONE][0]['value']['#value'] = 'Consultation appointment';
		  $form['field_cs_txt'][LANGUAGE_NONE][3]['field_cstxt_action'][LANGUAGE_NONE][0]['value']['#value'] = 'Surgery appointment';
		  $form['field_cs_txt'][LANGUAGE_NONE][4]['field_cstxt_action'][LANGUAGE_NONE][0]['value']['#value'] = '**Post surgery follow up 1';
		  $form['field_cs_txt'][LANGUAGE_NONE][5]['field_cstxt_action'][LANGUAGE_NONE][0]['value']['#value'] = '**Post surgery follow up 2';
		  $form['field_cs_txt'][LANGUAGE_NONE][6]['field_cstxt_action'][LANGUAGE_NONE][0]['value']['#value'] = '**Post surgery follow up 3';
		  $form['field_cs_txt'][LANGUAGE_NONE][7]['field_cstxt_action'][LANGUAGE_NONE][0]['value']['#value'] = 'Dental appointment';
		  $form['field_cs_txt'][LANGUAGE_NONE][8]['field_cstxt_action'][LANGUAGE_NONE][0]['value']['#value'] = '**Post dental follow up 1';
		  $form['field_cs_txt'][LANGUAGE_NONE][9]['field_cstxt_action'][LANGUAGE_NONE][0]['value']['#value'] = '**Post dental follow up 2';
	 	  $form['field_cs_txt'][LANGUAGE_NONE][10]['field_cstxt_action'][LANGUAGE_NONE][0]['value']['#value'] = 'Tour <tour name>';
		  $form['field_cs_txt'][LANGUAGE_NONE][11]['field_cstxt_action'][LANGUAGE_NONE][0]['value']['#value'] = 'Customer Satisfaction Feedback Email';
		  // Payment
		  $form['field_payment_details'][LANGUAGE_NONE][0]['field_payment_sections'][LANGUAGE_NONE][0]['value']['#value'] = "Airport Transfer";
		  $form['field_payment_details'][LANGUAGE_NONE][1]['field_payment_sections'][LANGUAGE_NONE][0]['value']['#value'] = "Accommodation";
		  $form['field_payment_details'][LANGUAGE_NONE][2]['field_payment_sections'][LANGUAGE_NONE][0]['value']['#value'] = "Dental Booking Fee";
		  $form['field_payment_details'][LANGUAGE_NONE][3]['field_payment_sections'][LANGUAGE_NONE][0]['value']['#value'] = "Surgery Booking Fee";
		  $form['field_payment_details'][LANGUAGE_NONE][4]['field_payment_sections'][LANGUAGE_NONE][0]['value']['#value'] = "Airfare";
		  $form['field_payment_details'][LANGUAGE_NONE][5]['field_payment_sections'][LANGUAGE_NONE][0]['value']['#value'] = "Tour";
		  $form['field_payment_details'][LANGUAGE_NONE][6]['field_payment_sections'][LANGUAGE_NONE][0]['value']['#value'] = "Tour";
		  $form['field_payment_details'][LANGUAGE_NONE][7]['field_payment_sections'][LANGUAGE_NONE][0]['value']['#value'] = "Tour";
		  $form['field_payment_details'][LANGUAGE_NONE][8]['field_payment_sections'][LANGUAGE_NONE][0]['value']['#value'] = "Tour";
		  
		 // Transfer
		 
		 $form['field_arrival_flight_details'][LANGUAGE_NONE][0]['field_transfers_from'][LANGUAGE_NONE][0]['value']['#value'] = 'Airport';
		 $form['field_arrival_flight_details'][LANGUAGE_NONE][0]['field_transfers_to'][LANGUAGE_NONE][0]['value']['#value'] = 'Hotel';
		 
		 
		 $form['field_departure_flight_details'][LANGUAGE_NONE][0]['field_transfers_from'][LANGUAGE_NONE][0]['value']['#value'] = 'Hotel';
		 $form['field_departure_flight_details'][LANGUAGE_NONE][0]['field_transfers_to'][LANGUAGE_NONE][0]['value']['#value'] = 'Airport';
		 $form['field_departure_flight_details'][LANGUAGE_NONE][0]['field_transfers_pickup_date'][LANGUAGE_NONE]['#access'] = 0;
		 
		}
		
		// Ajax functionality for Hotel Name & Room Type Start
		$form['field_hotel_name'][LANGUAGE_NONE]['#ajax'] = array(
      'callback' => 'ajax_room_type_callback',
      'wrapper' => 'room_type',
      'effect' => 'fade',
    );
    $form['field_room_type'][LANGUAGE_NONE]['#prefix'] = '<div id="room_type">';
    $form['field_room_type'][LANGUAGE_NONE]['#suffix'] = '</div>';
    
    if (
        isset($form_state['values']['field_hotel_name'][LANGUAGE_NONE][0]['tid']) && 
        $form_state['values']['field_hotel_name'][LANGUAGE_NONE][0]['tid'] == 93
     ) {
			$options = _get_room_type_options();
			$form['field_room_type'][LANGUAGE_NONE]['#options'] = array('_none' => '- None -') + $options[$form_state['values']['field_hotel_name'][LANGUAGE_NONE][0]['tid']];
		}
		else if (
		   (isset($form_state['values']['field_hotel_name'][LANGUAGE_NONE][0]['tid']) && 
		   $form_state['values']['field_hotel_name'][LANGUAGE_NONE][0]['tid'] == 92) 
		) {
			$options = _get_room_type_options();
			$form['field_room_type'][LANGUAGE_NONE]['#options'] = array('_none' => '- None -') + $options[$form_state['values']['field_hotel_name'][LANGUAGE_NONE][0]['tid']];
		}
		else if (isset($form_state['node']) && !empty($form_state['node']->field_hotel_name[LANGUAGE_NONE][0]['tid'])) {
			$options = _get_room_type_options();
			$form['field_room_type'][LANGUAGE_NONE]['#options'] = array('_none' => '- None -') + $options[$form_state['node']->field_hotel_name[LANGUAGE_NONE][0]['tid']];
		}
	  $form['#validate'][] = 'stu_schedule_validate';
	}
}


/**
 * Ajax callback
 */
function ajax_total_night_calcu_callback($form, $form_state) {
  return $form['field_no_nights'];
}

/**
 * Ajax callback
 */
function ajax_room_type_callback($form, $form_state) {
  return $form['field_room_type'];
}

/**
 * Ajax callback
 */
function ajax_total_cost_calcu_callback($form, $form_state) {
	return $form['field_total_cost'];
}

/**
 * Form makeovers_master_node_form - Custom Submit handler
 */
//~ function stu_schedule_submit($form, &$form_state) {
	//~ global $base_url;
	//~ $variables = array();
	//~ $node = $form_state['node'];
	//~ $values = $form_state['values'];
	//~ $wrapper = entity_metadata_wrapper('node', $node);
	//~ foreach ($wrapper->field_arrival_flight_details as $details) {
	  //~ echo $details->field_transfers_pickup_date->value();	
	//~ }
	//~ die;
//~ }


/**
 * Form makeovers_master_node_form - Custom Validate handler
 */
function stu_schedule_validate($form, &$form_state) {
	$values = $form_state['values'];
	if (!empty($form_state['values']['field_check_in_date'][LANGUAGE_NONE][0][value])) {
	  $checkin = strtotime($form_state['values']['field_check_in_date'][LANGUAGE_NONE][0][value]);
  }
  if (!empty($form_state['values']['field_check_out_date'][LANGUAGE_NONE][0][value])) {
	  $checkout = strtotime($form_state['values']['field_check_out_date'][LANGUAGE_NONE][0][value]);
	}
	
  if (($checkin && $checkout) && ($checkin > $checkout)) {
    form_set_error('field_check_in_date', 'Check In date should be greater than Check Out date.');
  }
}

/**
 * Options
 */
function _get_room_type_options() {
  $options[93] = array(
		'Superior Garden Wing Room' => 'Superior Garden Wing Room',
		'Superior Spa Wing Room' => 'Superior Spa Wing Room',
		'Deluxe Room with Jacuzzi' => 'Deluxe Room with Jacuzzi',
		'Junior Suite' => 'Junior Suite',
		'Executive Suite with Jacuzzi' => 'Executive Suite with Jacuzzi', 
		'Family Room' => 'Family Room',
	);
	$options[92] = array(
		'Premier Room' => 'Premier Room',
		'Dream Room' => 'Dream Room',
		'Premier Suite' => 'Premier Suite',
		'Dream Suite' => 'Dream Suite'  
	);
	return $options;
}


/**
 * Implementing Hook_mail()
 */
function stu_schedule_mail($key, &$message, $params) {
	$options = array(
    'langcode' => $message['language']->language,
  );
  switch ($key) {
    case 'hotalbooking':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
    break;
    case 'transfer':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
    break;
    case 'tour':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
    break;
    case 'cruise':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
    break;
  }
  
}

/**
 * Generate PDF
 */
function generate_pdf($node, $values) {
  global $base_url;
  $module_path = $base_url . '/' . drupal_get_path('module','stu_schedule') .'/MOSFiles';
  module_load_include('inc', 'print', 'includes/print');
	require 'sites/all/modules/print/dompdf/dompdf_config.inc.php';
	define("DOMPDF_ENABLE_PHP", TRUE);
  define("DOMPDF_ENABLE_REMOTE", TRUE);
  $merged_file_name = 'attachment'.$node->nid;
	$logo_url = theme_get_setting('logo');
  $print_logo = theme('image', array('path' => $logo_url, 'alt' => variable_get('site_name', 'Drupal'), 'attributes' => array('class' => 'print-logo', 'id' => 'logo')));
  
  //Hospital
	$field_hospital = $values[field_hospital][LANGUAGE_NONE][0][nid];
	
  if ($values[field_admit_type][LANGUAGE_NONE][0][value] == 'Daycare') {
    $html = theme('stunning_makeovers_schedule_daycare', array('values' => $values, 'node' => $node, 'print_logo' => $print_logo,));
  }
  else if ($values[field_admit_type][LANGUAGE_NONE][0][value] == 'Not Daycare') {
		$html = theme('stunning_makeovers_schedule_not_daycare', array('values' => $values, 'node' => $node, 'print_logo' => $print_logo,));
  }
  
  $html = str_replace('', '&#0128;', $html);
  if (function_exists('utf8_decode')) {
    $html = utf8_decode($html);
  }
  elseif (function_exists('mb_convert_encoding')) {
    $html = mb_convert_encoding($html, 'ISO-8859-1', 'UTF-8');
  }
  elseif (function_exists('recode_string')) {
    $html = recode_string('UTF-8..ISO_8859-1', $html);
  }
  $html = htmlspecialchars_decode(htmlentities($html, ENT_NOQUOTES, 'ISO-8859-1'), ENT_NOQUOTES);
  
  $dompdf = new DOMPDF();
  //$dompdf->set_paper(array(0,0,900,1000),'portrait');
  $data = '<html>';
  $data .= $html;
  $data .= '</html>';
  
  $dompdf->load_html($data);
  $dompdf->render();
  
  $path = 'public://schedule';
  file_prepare_directory($path, FILE_CREATE_DIRECTORY);
  $filename = $node->nid ;
  // Position at 1.5 cm from bottom
  $pdfoutput = $dompdf->output();
  $pdf_path = $path . '/' . $filename . '.pdf';
  $fp = fopen($pdf_path, "a");
  fwrite($fp, $pdfoutput);
  fclose($fp);
  
  // Attachment of pdf
  $field_hospital = $values[field_hospital][LANGUAGE_NONE][0][nid];
  $field_hotel_name = $values[field_hotel_name][LANGUAGE_NONE][0][tid];
  $field_dental_practice_options = $values[field_dental_practice_options][LANGUAGE_NONE][0][value];
	$field_client_hotel_name = $values[field_client_hotel_name][LANGUAGE_NONE][0][value];
  
  $files = array();
  
  // Air Ticket
  if ($node->field_upload_ticket[$node->language][0][fid]) {
    $files[] = drupal_realpath($node->field_upload_ticket[$node->language][0][uri]);
  }
  
  // MOS schedule
  if (file_exists($pdf_path)) {
    $files[] = drupal_realpath($pdf_path);
  }
  
  // Booth
  if ($field_hospital == 67) { //Vejthani International Hospital 
		$files[] = $module_path .'/Vejthani_Airport_Booth_Map.pdf';
    $files[] = $module_path .'/Vejthani_AOT_Pick_Up_Map.pdf';
  }
	else if ($field_hospital == 66) { //Yanhee International Hospital 
		$files[] = $module_path .'/Yanhee Aiport Pick Up Map.pdf';	
	}
  
  //~ //Hospital and/or Dental appointment forms
  //~ if ($node->field_upload_surgery[$node->language][0][fid]) {
    //~ $files[] = drupal_realpath($node->field_upload_surgery[$node->language][0][uri]);
  //~ }
  //~ if ($node->field_upload_dental[$node->language][0][fid]) {
    //~ $files[] = drupal_realpath($node->field_upload_dental[$node->language][0][uri]);
  //~ }
  //~ 
  //~ // Breakfast menu (if applicable)
  if ($field_hotel_name == 92) { // Dream Hotel
	  $files[] = $module_path .'/Stunning Makeovers Exclusive In-Room Breakfast Menu (Dream Hotel).pdf';
	}
  //~ 
  //~ // Information
  //~ if (stripos($field_dental_practice_options,'Bangpakok') !== false && empty($field_hospital)) {
    //~ if ($field_client_hotel_name) { // Own 
      //~ $files[] = $module_path .'/Information Pack Bangkok Surgery - Own Arrangements.pdf';
    //~ }
    //~ if ($field_hotel_name == 92) {
      //~ $files[] = $module_path .'/Information Pack Bangkok Dental - Dream Hotel Guests.pdf';
    //~ }
  //~ }
  //~ 
  //~ if (!empty($field_hospital) && $field_hospital != 731) {
    //~ if ($field_client_hotel_name) { // Own 
      //~ $files[] = $module_path .'/Information Pack Bangkok Surgery - Own Arrangements.pdf';
    //~ }
    //~ if ($field_hotel_name == 92) {
      //~ $files[] = $module_path .'/Information Pack Bangkok Surgery - Dream Hotel Guests.pdf';
    //~ }
  //~ }
  //~ 
  //~ if (stripos($field_dental_practice_options,'Phuket') !== false && empty($field_hospital)) {
    //~ if ($field_client_hotel_name) { // Own 
      //~ $files[] = $module_path .'/Information Pack Phuket Dental - Own Arrangements.pdf';
    //~ }
    //~ if ($field_hotel_name == 93) {
      //~ $files[] = $module_path .'/Information Pack Phuket Dental - Deevana Resort.pdf';
    //~ }
  //~ }
  //~ 
  //~ if (!empty($field_hospital) && $field_hospital == 731) {
    //~ if ($field_client_hotel_name) { // Own 
      //~ $files[] = $module_path .'/Information Pack Phuket Dental - Own Arrangements.pdf';
    //~ }
    //~ if ($field_hotel_name == 93) {
      //~ $files[] = $module_path .'/Information Pack Phuket Surgery - Deevana Resort.pdf';
    //~ }
  //~ }
  //~ 
  //~ // Hospital map
  //~ if ($field_hospital == 731) { //Phuket Plastic Surgery Institute 
	  //~ $files[] = $module_path .'/PPSI Hospital Map.pdf';
	//~ } 
	//~ else if ($field_hospital == 721) { //Bangpakok 9 International Hospital  
		//~ $files[] = $module_path .'/Bangpakok 9 Hospital Map.pdf';
	//~ } 
	//~ else if ($field_hospital == 67) { //Vejthani International Hospital 
		//~ $files[] = $module_path .'/Vejthani Hospital Map.pdf';
	//~ }
	//~ else if ($field_hospital == 66) { //Yanhee International Hospital 
		//~ $files[] = $module_path .'/Yanhee Hospital Map.pdf';	
	//~ }
  //~ 
  //~ // Hotel map
  //~ if ($field_hotel_name == 92) { // Dream Hotel
	  //~ $files[] = $module_path .'/Dream Hotel Map.pdf';
  //~ }
  //~ 
  //~ // Dental map
	//~ if ($field_dental_practice_options == 'Bangkok Smile Nana Sukhumvit Soi 5') {
	  //~ $files[] = $module_path .'/Bangkok Smile Soi 5 Practice Map.pdf';
	//~ }
	//~ else if ($field_dental_practice_options == 'Bangkok Smile ASOK Sukhumvit Soi 21') {
	  //~ $files[] = $module_path .'/Bangkok Smile Sukhumvit 21 Practice Map.pdf';
	//~ }
	//~ else if ($field_dental_practice_options == 'Bangkok Smile Ploenchit') {
	  //~ //$files[] = $module_path .'/';
	//~ }
	//~ else if ($field_dental_practice_options == 'Bangkok Silom Smile Studio') {
	  //~ //$files[] = $module_path .'/';
	//~ }
	//~ else if ($field_dental_practice_options == 'Phuket Sea Smile Dental Clinic (Jungceylon)') {
	  //~ $files[] = $module_path .'/Sea Smile Map Juncelyon.pdf';
	//~ }
	//~ else if ($field_dental_practice_options == 'Phuket Sea Smile International Dental Clinic') {
	  //~ $files[] = $module_path .'/Patong Smile (opp Holiday Inn) Practice Map.pdf';
	//~ }
	//~ else if ($field_dental_practice_options == 'Phuket Sea Smile @ The Kee Dental Clinic') {
	  //~ $files[] = $module_path .'/Sea Smile @THE KEE Dental Practice Map.pdf';
	//~ }
	
  $path = 'public://schedule';
  $apdf_path = $path . '/' . $merged_file_name . '.pdf';
  $afp = fopen($apdf_path, "a");
  fwrite($afp, '');
  fclose($afp);
  
  // Merge them.
  exec(escapeshellcmd('stamptk ' . implode($files, ' ') . ' cat output ' . drupal_realpath($apdf_path)));
  
  // @todo check status of 'exec' command.
  if ($uri && is_file($uri)) {
    
  }
  else {
    watchdog('pdf_merge',  'File %file was not created.', array('%file' => $uri), WATCHDOG_CRITICAL);
  }
  
  // pdf in textarea
  if(file_exists($pdf_path)) {
		$pdfurl = $base_url . '/sites/default/files/schedule/' . $merged_file_name . '.pdf?'.time();
    $node->field_pdf_data[$node->language][0][value] = "<iframe height='700' src='{$pdfurl}' width='100%'></iframe>";
    $node->field_pdf_data[$node->language][0][format] = 3;
    node_save($node);
    drupal_set_message(t('MOS pdf has been generated in the system, please see the preview at MOS PDF tab.'));
  }
  
  return $pdf_path;  
}

/**
 * Custom form to show a button at node view page
 */
function get_makeover_schedule($node, $form_state) {
  // Field Collection
	$node = $form_state['build_info']['args'][0];
	$wrapper = entity_metadata_wrapper('node', $node);
	$arrival_flight = $wrapper->field_arrival_flight_details->field_airport_transfer->value();
	$departure_flight = $wrapper->field_departure_flight_details->field_airport_transfer->value();
	$field_accommodation_arranged = $node->field_accommodation_arranged[LANGUAGE_NONE][0]['value'];
	
	$form['makeover_schedule'] = array(
    '#type' => 'submit',
    '#value' => t('Get Makeover Schedule'),
  );
  $form['makeover_schedule_mail'] = array(
    '#type' => 'submit',
    '#value' => t('Send to Coordinator'),
    '#submit' => array('makeover_schedule_mail_custom'),
  );
  if ($arrival_flight == 'Stunning Makeovers Limited' || $departure_flight == 'Stunning Makeovers Limited') {
		$form['makeover_schedule_mailtodriver'] = array(
			'#type' => 'submit',
			'#value' => t('Send Mail To Driver'),
			'#submit' => array('makeover_schedule_mail_custom'),
		);
	}
	if ($field_accommodation_arranged == 'Accommodation Arranged by Stunning Makeovers Limited') {
		$form['makeover_schedule_mailtohotel'] = array(
			'#type' => 'submit',
			'#value' => t('Send Mail To Hotel'),
			'#submit' => array('makeover_schedule_mail_custom'),
		);
	}
	if (sizeof($node->field_tour[LANGUAGE_NONE]) > 0) {
		$form['makeover_schedule_mailtotour'] = array(
			'#type' => 'submit',
			'#value' => t('Send Mail To Tour'),
			'#submit' => array('makeover_schedule_mail_custom'),
		);
	}
  return $form;
}

/**
 * Implementing hook_node_presave()
 */
function stu_schedule_node_presave($node) {
	if ($node->type == 'makeovers_master') {
    $field_check_in_date = $node->field_check_in_date[LANGUAGE_NONE][0]['value'];
	  $field_check_out_date = $node->field_check_out_date[LANGUAGE_NONE][0]['value'];
	  
	  $first_date = new DateTime($field_check_in_date);
    $second_date = new DateTime($field_check_out_date);
    $difference = $first_date->diff($second_date);
    if ($difference->d) {
      $node->field_no_nights[LANGUAGE_NONE][0]['value'] = $difference->d;
	  }
  }
}

/**
 * Implementing hook_node_view()
 */
function stu_schedule_node_view($node, $view_mode, $langcode) {
	if ($node->type == 'makeovers_master') {
    $node->content['my_additional_field'] = array(
      '#markup' => render(drupal_get_form('get_makeover_schedule',$node)),
    );
  }
}

/**
 * PDF generate callback function
 */
function get_makeover_schedule_submit($form, &$form_state) {
	$node = $form_state['build_info']['args'][0];
	$values = (array) $node;
	generate_pdf($node, $values);
}


/**
 * PDF generate callback function
 */
function makeover_schedule_mail_custom($form, &$form_state) {
  global $base_url;
	
	// Global Variables
  $variables['!logo'] = "<span style='margin:2px;'><img src='{$base_url}/sites/all/themes/smo/logo.png' width='200px' height='58px'></a></span>";
  $variables['!social_icons'] = "
  <div><table border=0 style='margin-top:-30px;' valign='top'>
  <tr>
  <td valign='top'><a href='https://www.facebook.com/stunningmakeovers'>
  <img src='{$base_url}/sites/all/themes/smo/images/mailicon.png'/></a></td>
  <td valign='top'><a href='http://www.stunningmakeovers.com/index.php?option=com_facileforms&Itemid=57'>
  <img src='{$base_url}/sites/all/themes/smo/images/mailcontact.png'/></a></td>
  <td valign='top'><a href='http://www.stunningmakeovers.com/'>
  <img src='{$base_url}/sites/all/themes/smo/images/mailhome.png'/></a></td>
  </tr>
  </table></div>";
	
	$node = $form_state['build_info']['args'][0];
	$values = (array) $node;
  
  // Field Collection
	$wrapper = entity_metadata_wrapper('node', $node);

	// Client Details
	$field_room_type = $values[field_room_type][LANGUAGE_NONE][0][value];
	$field_clients_passport_name = $values[field_clients_passport_name][LANGUAGE_NONE][0][value];
	$field_clients_preferred_name = $values[field_clients_preferred_name][LANGUAGE_NONE][0][value];
	$field_contact_phone_no = $values[field_contact_phone_no][LANGUAGE_NONE][0][value];
	$field_custom_title = $values[field_custom_title][LANGUAGE_NONE][0][value];

	$guestname = $field_custom_title . ''. ($node->title) ? $node->title : $field_clients_preferred_name;
	$variables['!client_name'] = $guestname;

	//Accommodation Arranged by Stunning Makeovers Limited
	$field_mm_accommodation = $values[field_mm_accommodation][LANGUAGE_NONE][0][value];
	$field_hotel_name = $values[field_hotel_name][LANGUAGE_NONE][0][tid];
	$field_room_type = $values[field_room_type][LANGUAGE_NONE][0][value];
	$field_check_in_date = $values[field_check_in_date][LANGUAGE_NONE][0][value];
	$field_check_out_date = $values[field_check_out_date][LANGUAGE_NONE][0][value];
	$field_no_nights = $values[field_no_nights][LANGUAGE_NONE][0][value];
	$field_qualify_for_upgrade = $values[field_qualify_for_upgrade][LANGUAGE_NONE][0][value];
	$field_upgrade_room_type = $values[field_upgrade_room_type][LANGUAGE_NONE][0][value];
	$field_bedding = $values[field_bedding][LANGUAGE_NONE][0][value];
	$field_rollaway_bed_required = $values[field_rollaway_bed_required][LANGUAGE_NONE][0][value];

	$field_primary_guest = $values[field_primary_guest][LANGUAGE_NONE][0][value];
	$field_guest_2 = $values[field_guest_2][LANGUAGE_NONE][0][value];
	$field_guest_3 = $values[field_guest_3][LANGUAGE_NONE][0][value];
	$field_guest_4 = $values[field_guest_4][LANGUAGE_NONE][0][value];
	$field_cost_per_night_thb = $values[field_cost_per_night_thb][LANGUAGE_NONE][0][value];
	$field_cost_for_rollaway_bed = $values[field_cost_for_rollaway_bed][LANGUAGE_NONE][0][value];
	$field_total_cost = $values[field_total_cost][LANGUAGE_NONE][0][value];
	$field_hotel_providing_airport = $values[field_hotel_providing_airport][LANGUAGE_NONE][0][value];
	$field_hotel_booking_confirmation = $values[field_hotel_booking_confirmation][LANGUAGE_NONE][0][value];
	$field_own_accom_details = $values[field_own_accom_details][LANGUAGE_NONE][0][value];

	//Hospital
	$field_hospital = $values[field_hospital][LANGUAGE_NONE][0][nid];
	$field_consultation_before_surger = $values[field_consultation_before_surger][LANGUAGE_NONE][0][value];
	$field_consultation_date = $values[field_consultation_date][LANGUAGE_NONE][0][value];
	$field_surgery_date = $values[field_surgery_date][LANGUAGE_NONE][0][value];
	$field_transfer_for_consultation = $values[field_transfer_for_consultation][LANGUAGE_NONE][0][value];
	$field_hospital_transfer_time = $values[field_hospital_transfer_time][LANGUAGE_NONE][0][value];
	$field_consultation_appointment = $values[field_consultation_appointment][LANGUAGE_NONE][0][value];

	$field_mm_surgeon = $values[field_mm_surgeon][LANGUAGE_NONE][0][nid];
	$field_mm_coordinator = $values[field_mm_coordinator][LANGUAGE_NONE][0][value];
	$field_surgery_appointment_date = $values[field_surgery_appointment_date][LANGUAGE_NONE][0][value];
	$field_transfer_surgery_appoint = $values[field_transfer_surgery_appoint][LANGUAGE_NONE][0][value];
	$field_surgery_appoint_tran_time = $values[field_surgery_appoint_tran_time][LANGUAGE_NONE][0][value];
	$field_surgery_appointment = $values[field_surgery_appointment][LANGUAGE_NONE][0][value];
  
  //Flight Arrival
  if (sizeof($wrapper->field_arrival_flight_details) > 0) {
    $arrival_field_airport_transfer = $wrapper->field_arrival_flight_details->field_airport_transfer->value();
    if ($arrival_field_airport_transfer == 'Stunning Makeovers Limited') {
	    $variables['!date_of_first_transfer'] = date('l, jS F, Y h:ia', $wrapper->field_arrival_flight_details->field_transfers_pickup_date->value());
    }
  }
  //Flight Departure
  if (sizeof($wrapper->field_departure_flight_details) > 0) {
		$departure_field_airport_transfer = $wrapper->field_departure_flight_details->field_airport_transfer->value();
		if ($arrival_field_airport_transfer != 'Stunning Makeovers Limited' && $departure_field_airport_transfer == 'Stunning Makeovers Limited') {
		  $variables['!date_of_first_transfer'] = date('l, jS F, Y h:ia', $wrapper->field_departure_flight_details->field_transfers_pickup_date->value());
		  $transfers_pickup_date = $wrapper->field_departure_flight_details->field_transfers_pickup_date->value();
		}
	}
  
  //Tour
  $field_send_mail_tour = $values[field_send_mail_tour][LANGUAGE_NONE][0][value];
  $field_tour = $values[field_tour][LANGUAGE_NONE][0][value];
  $field_clients_preferred_name = $values[field_clients_preferred_name][und][0][value];
  $op = $form_state['values']['op'];
	switch ($op) {
    case 'Send to Coordinator':
        _send_mail_to_client($node, $variables);
        break;
    
    case 'Send Mail To Driver':
		$transfer_details = theme(
		  'transfers_stunning_makeovers', 
		   array(
			  'guestname' => $guestname,
			  'guestname2' => $field_guest_2,
			  'guestname3' => $field_guest_3,
			  'guestname4' => $field_guest_4,
			  'arrival' => ($arrival_field_airport_transfer == 'Stunning Makeovers Limited') ? $wrapper->field_arrival_flight_details : null,
			  'departure' => ($departure_field_airport_transfer == 'Stunning Makeovers Limited') ? $wrapper->field_departure_flight_details : null
		   )
		 );
		 $variables['!transfer_details'] = $transfer_details;
		_send_transfer_mail($variables);
        break;
        
    case 'Send Mail To Hotel':
    if ($wrapper->field_check_in_date->value()) {
      $field_check_in_date = date('l, jS M Y', $wrapper->field_check_in_date->value());
      $variables['!check_in_date'] = date('l, jS M Y', $wrapper->field_check_in_date->value());
		}
		if ($wrapper->field_check_out_date->value()) {
	    $field_check_out_date = date('l, jS M Y', $wrapper->field_check_out_date->value());
	    $variables['!check_out_date'] = date('l, jS M Y', $wrapper->field_check_out_date->value());
	  }
		$booking_details = theme(
		'hotel_reservation', 
		 array(
			'guestname' => $guestname, 
			'guestname2' => $field_guest_2,
			'guestname3' => $field_guest_3,
			'guestname4' => $field_guest_4, 
			'bedding' => $field_bedding, 
			'checkin' => $field_check_in_date,
			'checkout' => $field_check_out_date,
			'roomtype' => $field_room_type,
			'ratepernight' => ($field_cost_per_night_thb + $field_cost_for_rollaway_bed),
			'numberofnights' => $field_no_nights,
			'totalpayable' => $field_total_cost,
			'hoteltoairport' => $transfers_pickup_date,
			'hotelname' => $field_hotel_name,
			'rollaway_bed' => $field_rollaway_bed_required,
			'qualify_for_upgrade' => $field_qualify_for_upgrade,
			'upgrade_room_type' => $field_upgrade_room_type,
		 )
		);
		$variables['!booking_details'] = $booking_details;
    echo $field_hotel_name;
    die;
		_send_mail_to_hotel($field_hotel_name, $variables);
        break;
    
    case 'Send Mail To Tour':
    $cruise = false;
		$othertour = false;
		foreach ($wrapper->field_tour as $tours) {
			if ($tours->field_tour_name->value() == 'Chaophraya River Dinner Cruise') {
				$cruise = true;
				$variables['!cruise_date'] = date('l, jS M Y',$tours->field_tour_date_time->value());
			}
			else if ($tours->field_tour_name->value() != 'Chaophraya River Dinner Cruise' && !empty($tours->field_tour_name->value())) {
				$othertour = true;
				$variables['!othertour_date'] = date('l, jS M Y',$tours->field_tour_date_time->value());	
			}
		}
		
		// Send mail for tour
		if ($othertour) {
			$tour_details = theme(
			 'tours_stunning_makeovers', 
				 array(
					'guestname' => ($field_clients_preferred_name) ? $field_clients_preferred_name : $guestname,
					'guestname2' => $field_guest_2,
					'guestname3' => $field_guest_3,
					'guestname4' => $field_guest_4,
					'iterations' => $wrapper->field_tour,
				 )
			);
			$variables['!tour_details'] = $tour_details;
			_send_tour_mail($variables);
		}
					
		// Send mail for cruise
		if ($cruise) {
			$cruise_details = theme(
			 'cruise_stunning_makeovers', 
				 array(
					'guestname' => ($field_clients_preferred_name) ? $field_clients_preferred_name : $guestname,
					'guestname2' => $field_guest_2,
					'guestname3' => $field_guest_3,
					'guestname4' => $field_guest_4,
					'iterations' => $wrapper->field_tour,
				 )
			);
			$variables['!cruise_details'] = $cruise_details;
			_send_cruise_mail($variables);
		}
        break;
    
    default:
  }
}
