<?php
/**
 * Implements hook_block_info()
 */
function stu_procedurelist_block_info() {
  $blocks['procedure_group'] = array(
    'info' => t('STU Procedure Group'),
    'status' => TRUE,
    'cache' => DRUPAL_NO_CACHE,
    'region' => -1,
  );
  return $blocks;
}

/**
 * Implementing hook_block_view()
 */
function stu_procedurelist_block_view($delta = '') {
	$block = array();
  switch ($delta) {
		case 'procedure_group':
      $block['subject'] = t('STU Procedure Group');
      $block['content'] = stu_procedurelist_get_block();
    break;
  }
	return $block;
}

function stu_procedurelist_get_block() {
	$output = theme('stu_procedurelist');
	return   $output;  
}

/**
 * Implementing hook_theme()
 */
function stu_procedurelist_theme($existing, $type, $theme, $path) {
	return array(
		'stu_procedurelist' => array(
		  'variables' => array(),
		  'template' => 'stu_procedurelist',
		),		
	); 
}
